/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Effekseer {

using System;
using System.Runtime.InteropServices;


[System.Security.SuppressUnmanagedCodeSecurity]
class EffekseerNativePINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [DllImport("Viewer", EntryPoint="SWIGRegisterExceptionCallbacks_EffekseerNative")]
    public static extern void SWIGRegisterExceptionCallbacks_EffekseerNative(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [DllImport("Viewer", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_EffekseerNative")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_EffekseerNative(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_EffekseerNative(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_EffekseerNative(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [ThreadStatic]
    private static Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(Exception e) {
      if (pendingException != null)
        throw new ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(EffekseerNativePINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static Exception Retrieve() {
      Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(EffekseerNativePINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [DllImport("Viewer", EntryPoint="SWIGRegisterStringCallback_EffekseerNative")]
    public static extern void SWIGRegisterStringCallback_EffekseerNative(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_EffekseerNative(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static EffekseerNativePINVOKE() {
  }


  protected class SWIGWStringHelper {

    public delegate string SWIGWStringDelegate(IntPtr message);
    static SWIGWStringDelegate wstringDelegate = new SWIGWStringDelegate(CreateWString);

    [DllImport("Viewer", EntryPoint="SWIGRegisterWStringCallback_EffekseerNative")]
    public static extern void SWIGRegisterWStringCallback_EffekseerNative(SWIGWStringDelegate wstringDelegate);

    static string CreateWString([MarshalAs(UnmanagedType.LPWStr)]IntPtr cString) {
      return System.Runtime.InteropServices.Marshal.PtrToStringUni(cString);
    }

    static SWIGWStringHelper() {
      SWIGRegisterWStringCallback_EffekseerNative(wstringDelegate);
    }
  }

  static protected SWIGWStringHelper swigWStringHelper = new SWIGWStringHelper();


  [DllImport("Viewer", EntryPoint="CSharp_ViewerParamater_GuideWidth_set")]
  public static extern void ViewerParamater_GuideWidth_set(HandleRef jarg1, int jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerParamater_GuideWidth_get")]
  public static extern int ViewerParamater_GuideWidth_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerParamater_GuideHeight_set")]
  public static extern void ViewerParamater_GuideHeight_set(HandleRef jarg1, int jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerParamater_GuideHeight_get")]
  public static extern int ViewerParamater_GuideHeight_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerParamater_RateOfMagnification_set")]
  public static extern void ViewerParamater_RateOfMagnification_set(HandleRef jarg1, float jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerParamater_RateOfMagnification_get")]
  public static extern float ViewerParamater_RateOfMagnification_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerParamater_IsPerspective_set")]
  public static extern void ViewerParamater_IsPerspective_set(HandleRef jarg1, bool jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerParamater_IsPerspective_get")]
  public static extern bool ViewerParamater_IsPerspective_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerParamater_IsOrthographic_set")]
  public static extern void ViewerParamater_IsOrthographic_set(HandleRef jarg1, bool jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerParamater_IsOrthographic_get")]
  public static extern bool ViewerParamater_IsOrthographic_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerParamater_FocusX_set")]
  public static extern void ViewerParamater_FocusX_set(HandleRef jarg1, float jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerParamater_FocusX_get")]
  public static extern float ViewerParamater_FocusX_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerParamater_FocusY_set")]
  public static extern void ViewerParamater_FocusY_set(HandleRef jarg1, float jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerParamater_FocusY_get")]
  public static extern float ViewerParamater_FocusY_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerParamater_FocusZ_set")]
  public static extern void ViewerParamater_FocusZ_set(HandleRef jarg1, float jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerParamater_FocusZ_get")]
  public static extern float ViewerParamater_FocusZ_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerParamater_AngleX_set")]
  public static extern void ViewerParamater_AngleX_set(HandleRef jarg1, float jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerParamater_AngleX_get")]
  public static extern float ViewerParamater_AngleX_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerParamater_AngleY_set")]
  public static extern void ViewerParamater_AngleY_set(HandleRef jarg1, float jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerParamater_AngleY_get")]
  public static extern float ViewerParamater_AngleY_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerParamater_Distance_set")]
  public static extern void ViewerParamater_Distance_set(HandleRef jarg1, float jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerParamater_Distance_get")]
  public static extern float ViewerParamater_Distance_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerParamater_RendersGuide_set")]
  public static extern void ViewerParamater_RendersGuide_set(HandleRef jarg1, bool jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerParamater_RendersGuide_get")]
  public static extern bool ViewerParamater_RendersGuide_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_new_ViewerParamater")]
  public static extern IntPtr new_ViewerParamater();

  [DllImport("Viewer", EntryPoint="CSharp_delete_ViewerParamater")]
  public static extern void delete_ViewerParamater(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_CountX_set")]
  public static extern void ViewerEffectBehavior_CountX_set(HandleRef jarg1, int jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_CountX_get")]
  public static extern int ViewerEffectBehavior_CountX_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_CountY_set")]
  public static extern void ViewerEffectBehavior_CountY_set(HandleRef jarg1, int jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_CountY_get")]
  public static extern int ViewerEffectBehavior_CountY_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_CountZ_set")]
  public static extern void ViewerEffectBehavior_CountZ_set(HandleRef jarg1, int jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_CountZ_get")]
  public static extern int ViewerEffectBehavior_CountZ_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_Distance_set")]
  public static extern void ViewerEffectBehavior_Distance_set(HandleRef jarg1, float jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_Distance_get")]
  public static extern float ViewerEffectBehavior_Distance_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_RemovedTime_set")]
  public static extern void ViewerEffectBehavior_RemovedTime_set(HandleRef jarg1, int jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_RemovedTime_get")]
  public static extern int ViewerEffectBehavior_RemovedTime_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_PositionX_set")]
  public static extern void ViewerEffectBehavior_PositionX_set(HandleRef jarg1, float jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_PositionX_get")]
  public static extern float ViewerEffectBehavior_PositionX_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_PositionY_set")]
  public static extern void ViewerEffectBehavior_PositionY_set(HandleRef jarg1, float jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_PositionY_get")]
  public static extern float ViewerEffectBehavior_PositionY_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_PositionZ_set")]
  public static extern void ViewerEffectBehavior_PositionZ_set(HandleRef jarg1, float jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_PositionZ_get")]
  public static extern float ViewerEffectBehavior_PositionZ_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_RotationX_set")]
  public static extern void ViewerEffectBehavior_RotationX_set(HandleRef jarg1, float jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_RotationX_get")]
  public static extern float ViewerEffectBehavior_RotationX_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_RotationY_set")]
  public static extern void ViewerEffectBehavior_RotationY_set(HandleRef jarg1, float jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_RotationY_get")]
  public static extern float ViewerEffectBehavior_RotationY_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_RotationZ_set")]
  public static extern void ViewerEffectBehavior_RotationZ_set(HandleRef jarg1, float jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_RotationZ_get")]
  public static extern float ViewerEffectBehavior_RotationZ_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_ScaleX_set")]
  public static extern void ViewerEffectBehavior_ScaleX_set(HandleRef jarg1, float jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_ScaleX_get")]
  public static extern float ViewerEffectBehavior_ScaleX_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_ScaleY_set")]
  public static extern void ViewerEffectBehavior_ScaleY_set(HandleRef jarg1, float jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_ScaleY_get")]
  public static extern float ViewerEffectBehavior_ScaleY_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_ScaleZ_set")]
  public static extern void ViewerEffectBehavior_ScaleZ_set(HandleRef jarg1, float jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_ScaleZ_get")]
  public static extern float ViewerEffectBehavior_ScaleZ_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_PositionVelocityX_set")]
  public static extern void ViewerEffectBehavior_PositionVelocityX_set(HandleRef jarg1, float jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_PositionVelocityX_get")]
  public static extern float ViewerEffectBehavior_PositionVelocityX_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_PositionVelocityY_set")]
  public static extern void ViewerEffectBehavior_PositionVelocityY_set(HandleRef jarg1, float jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_PositionVelocityY_get")]
  public static extern float ViewerEffectBehavior_PositionVelocityY_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_PositionVelocityZ_set")]
  public static extern void ViewerEffectBehavior_PositionVelocityZ_set(HandleRef jarg1, float jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_PositionVelocityZ_get")]
  public static extern float ViewerEffectBehavior_PositionVelocityZ_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_RotationVelocityX_set")]
  public static extern void ViewerEffectBehavior_RotationVelocityX_set(HandleRef jarg1, float jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_RotationVelocityX_get")]
  public static extern float ViewerEffectBehavior_RotationVelocityX_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_RotationVelocityY_set")]
  public static extern void ViewerEffectBehavior_RotationVelocityY_set(HandleRef jarg1, float jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_RotationVelocityY_get")]
  public static extern float ViewerEffectBehavior_RotationVelocityY_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_RotationVelocityZ_set")]
  public static extern void ViewerEffectBehavior_RotationVelocityZ_set(HandleRef jarg1, float jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_RotationVelocityZ_get")]
  public static extern float ViewerEffectBehavior_RotationVelocityZ_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_ScaleVelocityX_set")]
  public static extern void ViewerEffectBehavior_ScaleVelocityX_set(HandleRef jarg1, float jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_ScaleVelocityX_get")]
  public static extern float ViewerEffectBehavior_ScaleVelocityX_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_ScaleVelocityY_set")]
  public static extern void ViewerEffectBehavior_ScaleVelocityY_set(HandleRef jarg1, float jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_ScaleVelocityY_get")]
  public static extern float ViewerEffectBehavior_ScaleVelocityY_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_ScaleVelocityZ_set")]
  public static extern void ViewerEffectBehavior_ScaleVelocityZ_set(HandleRef jarg1, float jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_ViewerEffectBehavior_ScaleVelocityZ_get")]
  public static extern float ViewerEffectBehavior_ScaleVelocityZ_get(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_new_ViewerEffectBehavior")]
  public static extern IntPtr new_ViewerEffectBehavior();

  [DllImport("Viewer", EntryPoint="CSharp_delete_ViewerEffectBehavior")]
  public static extern void delete_ViewerEffectBehavior(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_new_Native")]
  public static extern IntPtr new_Native();

  [DllImport("Viewer", EntryPoint="CSharp_delete_Native")]
  public static extern void delete_Native(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_Native_CreateWindow_Effekseer")]
  public static extern bool Native_CreateWindow_Effekseer(HandleRef jarg1, IntPtr jarg2, int jarg3, int jarg4);

  [DllImport("Viewer", EntryPoint="CSharp_Native_UpdateWindow")]
  public static extern bool Native_UpdateWindow(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_Native_ResizeWindow")]
  public static extern bool Native_ResizeWindow(HandleRef jarg1, int jarg2, int jarg3);

  [DllImport("Viewer", EntryPoint="CSharp_Native_DestroyWindow")]
  public static extern bool Native_DestroyWindow(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_Native_LoadEffect")]
  public static extern bool Native_LoadEffect(HandleRef jarg1, IntPtr jarg2, int jarg3, [MarshalAs(UnmanagedType.LPWStr)]string jarg4);

  [DllImport("Viewer", EntryPoint="CSharp_Native_RemoveEffect")]
  public static extern bool Native_RemoveEffect(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_Native_PlayEffect")]
  public static extern bool Native_PlayEffect(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_Native_StopEffect")]
  public static extern bool Native_StopEffect(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_Native_StepEffect__SWIG_0")]
  public static extern bool Native_StepEffect__SWIG_0(HandleRef jarg1, int jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_Native_StepEffect__SWIG_1")]
  public static extern bool Native_StepEffect__SWIG_1(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_Native_Rotate")]
  public static extern bool Native_Rotate(HandleRef jarg1, float jarg2, float jarg3);

  [DllImport("Viewer", EntryPoint="CSharp_Native_Slide")]
  public static extern bool Native_Slide(HandleRef jarg1, float jarg2, float jarg3);

  [DllImport("Viewer", EntryPoint="CSharp_Native_Zoom")]
  public static extern bool Native_Zoom(HandleRef jarg1, float jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_Native_SetRandomSeed")]
  public static extern bool Native_SetRandomSeed(HandleRef jarg1, int jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_Native_Record")]
  public static extern bool Native_Record(HandleRef jarg1, [MarshalAs(UnmanagedType.LPWStr)]string jarg2, int jarg3, int jarg4, int jarg5, int jarg6, bool jarg7);

  [DllImport("Viewer", EntryPoint="CSharp_Native_GetViewerParamater")]
  public static extern IntPtr Native_GetViewerParamater(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_Native_SetViewerParamater")]
  public static extern void Native_SetViewerParamater(HandleRef jarg1, HandleRef jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_Native_GetEffectBehavior")]
  public static extern IntPtr Native_GetEffectBehavior(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_Native_SetViewerEffectBehavior")]
  public static extern void Native_SetViewerEffectBehavior(HandleRef jarg1, HandleRef jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_Native_SetSoundMute")]
  public static extern bool Native_SetSoundMute(HandleRef jarg1, bool jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_Native_SetSoundVolume")]
  public static extern bool Native_SetSoundVolume(HandleRef jarg1, float jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_Native_InvalidateTextureCache")]
  public static extern bool Native_InvalidateTextureCache(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_Native_SetIsGridShown")]
  public static extern void Native_SetIsGridShown(HandleRef jarg1, bool jarg2, bool jarg3, bool jarg4, bool jarg5);

  [DllImport("Viewer", EntryPoint="CSharp_Native_SetGridLength")]
  public static extern void Native_SetGridLength(HandleRef jarg1, float jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_Native_SetBackgroundColor")]
  public static extern void Native_SetBackgroundColor(HandleRef jarg1, byte jarg2, byte jarg3, byte jarg4);

  [DllImport("Viewer", EntryPoint="CSharp_Native_SetBackgroundImage")]
  public static extern void Native_SetBackgroundImage(HandleRef jarg1, [MarshalAs(UnmanagedType.LPWStr)]string jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_Native_SetGridColor")]
  public static extern void Native_SetGridColor(HandleRef jarg1, byte jarg2, byte jarg3, byte jarg4, byte jarg5);

  [DllImport("Viewer", EntryPoint="CSharp_Native_SetMouseInverseFlag")]
  public static extern void Native_SetMouseInverseFlag(HandleRef jarg1, bool jarg2, bool jarg3, bool jarg4, bool jarg5);

  [DllImport("Viewer", EntryPoint="CSharp_Native_SetStep")]
  public static extern void Native_SetStep(HandleRef jarg1, int jarg2);

  [DllImport("Viewer", EntryPoint="CSharp_Native_StartNetwork")]
  public static extern bool Native_StartNetwork(HandleRef jarg1, string jarg2, ushort jarg3);

  [DllImport("Viewer", EntryPoint="CSharp_Native_StopNetwork")]
  public static extern void Native_StopNetwork(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_Native_IsConnectingNetwork")]
  public static extern bool Native_IsConnectingNetwork(HandleRef jarg1);

  [DllImport("Viewer", EntryPoint="CSharp_Native_SendDataByNetwork")]
  public static extern void Native_SendDataByNetwork(HandleRef jarg1, [MarshalAs(UnmanagedType.LPWStr)]string jarg2, IntPtr jarg3, int jarg4, [MarshalAs(UnmanagedType.LPWStr)]string jarg5);

  [DllImport("Viewer", EntryPoint="CSharp_Native_SetLightDirection")]
  public static extern void Native_SetLightDirection(HandleRef jarg1, float jarg2, float jarg3, float jarg4);

  [DllImport("Viewer", EntryPoint="CSharp_Native_SetLightColor")]
  public static extern void Native_SetLightColor(HandleRef jarg1, byte jarg2, byte jarg3, byte jarg4, byte jarg5);

  [DllImport("Viewer", EntryPoint="CSharp_Native_SetLightAmbientColor")]
  public static extern void Native_SetLightAmbientColor(HandleRef jarg1, byte jarg2, byte jarg3, byte jarg4, byte jarg5);

  [DllImport("Viewer", EntryPoint="CSharp_Native_SetIsRightHand")]
  public static extern void Native_SetIsRightHand(HandleRef jarg1, bool jarg2);
}

}
