//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Effekseer.swig {

public class MainWindow : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal MainWindow(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MainWindow obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~MainWindow() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          EffekseerNativePINVOKE.delete_MainWindow(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public MainWindow() : this(EffekseerNativePINVOKE.new_MainWindow(), true) {
  }

  public static MainWindow GetInstance() {
    global::System.IntPtr cPtr = EffekseerNativePINVOKE.MainWindow_GetInstance();
    MainWindow ret = (cPtr == global::System.IntPtr.Zero) ? null : new MainWindow(cPtr, true);
    return ret;
  }

  public MainWindowState GetState() {
    MainWindowState ret = new MainWindowState(EffekseerNativePINVOKE.MainWindow_GetState(swigCPtr), true);
    if (EffekseerNativePINVOKE.SWIGPendingException.Pending) throw EffekseerNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetState(MainWindowState state) {
    EffekseerNativePINVOKE.MainWindow_SetState(swigCPtr, MainWindowState.getCPtr(state));
    if (EffekseerNativePINVOKE.SWIGPendingException.Pending) throw EffekseerNativePINVOKE.SWIGPendingException.Retrieve();
  }

  public float GetDPIScale() {
    float ret = EffekseerNativePINVOKE.MainWindow_GetDPIScale(swigCPtr);
    if (EffekseerNativePINVOKE.SWIGPendingException.Pending) throw EffekseerNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool IsFrameless() {
    bool ret = EffekseerNativePINVOKE.MainWindow_IsFrameless(swigCPtr);
    if (EffekseerNativePINVOKE.SWIGPendingException.Pending) throw EffekseerNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool Initialize(string title, MainWindowState state, bool isSRGBMode, bool isOpenGLMode) {
    bool ret = EffekseerNativePINVOKE.MainWindow_Initialize(title, MainWindowState.getCPtr(state), isSRGBMode, isOpenGLMode);
    if (EffekseerNativePINVOKE.SWIGPendingException.Pending) throw EffekseerNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void Terminate() {
    EffekseerNativePINVOKE.MainWindow_Terminate();
  }

}

}
