//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Effekseer.swig {

public enum TreeNodeFlags {
  None = 0,
  Selected = 1 << 0,
  Framed = 1 << 1,
  AllowItemOverlap = 1 << 2,
  NoTreePushOnOpen = 1 << 3,
  NoAutoOpenOnLog = 1 << 4,
  DefaultOpen = 1 << 5,
  OpenOnDoubleClick = 1 << 6,
  OpenOnArrow = 1 << 7,
  Leaf = 1 << 8,
  Bullet = 1 << 9,
  FramePadding = 1 << 10
}

}
