//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Effekseer.swig {

public class ColorF : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ColorF(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ColorF obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ColorF obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ColorF() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          EffekseerNativePINVOKE.delete_ColorF(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public float R {
    set {
      EffekseerNativePINVOKE.ColorF_R_set(swigCPtr, value);
    } 
    get {
      float ret = EffekseerNativePINVOKE.ColorF_R_get(swigCPtr);
      return ret;
    } 
  }

  public float G {
    set {
      EffekseerNativePINVOKE.ColorF_G_set(swigCPtr, value);
    } 
    get {
      float ret = EffekseerNativePINVOKE.ColorF_G_get(swigCPtr);
      return ret;
    } 
  }

  public float B {
    set {
      EffekseerNativePINVOKE.ColorF_B_set(swigCPtr, value);
    } 
    get {
      float ret = EffekseerNativePINVOKE.ColorF_B_get(swigCPtr);
      return ret;
    } 
  }

  public float A {
    set {
      EffekseerNativePINVOKE.ColorF_A_set(swigCPtr, value);
    } 
    get {
      float ret = EffekseerNativePINVOKE.ColorF_A_get(swigCPtr);
      return ret;
    } 
  }

  public ColorF() : this(EffekseerNativePINVOKE.new_ColorF__SWIG_0(), true) {
  }

  public ColorF(float r, float g, float b, float a) : this(EffekseerNativePINVOKE.new_ColorF__SWIG_1(r, g, b, a), true) {
  }

}

}
