//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Effekseer.swig {

public enum ComboFlags : int {
  None = ImGuiComboFlags_None,
  PopupAlignLeft = ImGuiComboFlags_PopupAlignLeft,
  HeightSmall = ImGuiComboFlags_HeightSmall,
  HeightRegular = ImGuiComboFlags_HeightRegular,
  HeightLarge = ImGuiComboFlags_HeightLarge,
  HeightLargest = ImGuiComboFlags_HeightLargest,
  NoArrowButton = ImGuiComboFlags_NoArrowButton,
  NoPreview = ImGuiComboFlags_NoPreview
}

}
