//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Effekseer.swig {

public class EffectRecorder : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal EffectRecorder(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(EffectRecorder obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~EffectRecorder() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          EffekseerNativePINVOKE.delete_EffectRecorder(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public bool Begin(int squareMaxCount, EffectRendererParameter config, Vector2I screenSize, GraphicsDevice graphicsDevice, EffectSetting setting, RecordingParameter recordingParameter, Vector2I imageSize, bool isSRGBMode, ViewerEffectBehavior behavior, ViewerExternalModelVector externalModels, PostEffectParameter postEffectParameter, Effect effect) {
    bool ret = EffekseerNativePINVOKE.EffectRecorder_Begin(swigCPtr, squareMaxCount, EffectRendererParameter.getCPtr(config), Vector2I.getCPtr(screenSize), GraphicsDevice.getCPtr(graphicsDevice), EffectSetting.getCPtr(setting), RecordingParameter.getCPtr(recordingParameter), Vector2I.getCPtr(imageSize), isSRGBMode, ViewerEffectBehavior.getCPtr(behavior), ViewerExternalModelVector.getCPtr(externalModels), PostEffectParameter.getCPtr(postEffectParameter), Effect.getCPtr(effect));
    if (EffekseerNativePINVOKE.SWIGPendingException.Pending) throw EffekseerNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool Step(int frames) {
    bool ret = EffekseerNativePINVOKE.EffectRecorder_Step(swigCPtr, frames);
    if (EffekseerNativePINVOKE.SWIGPendingException.Pending) throw EffekseerNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool End() {
    bool ret = EffekseerNativePINVOKE.EffectRecorder_End(swigCPtr);
    if (EffekseerNativePINVOKE.SWIGPendingException.Pending) throw EffekseerNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool IsCompleted() {
    bool ret = EffekseerNativePINVOKE.EffectRecorder_IsCompleted(swigCPtr);
    if (EffekseerNativePINVOKE.SWIGPendingException.Pending) throw EffekseerNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float GetProgress() {
    float ret = EffekseerNativePINVOKE.EffectRecorder_GetProgress(swigCPtr);
    if (EffekseerNativePINVOKE.SWIGPendingException.Pending) throw EffekseerNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public EffectRecorder() : this(EffekseerNativePINVOKE.new_EffectRecorder(), true) {
  }

}

}
