//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Effekseer.swig {

public class GUIManager : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GUIManager(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GUIManager obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(GUIManager obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~GUIManager() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          EffekseerNativePINVOKE.delete_GUIManager(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public GUIManager() : this(EffekseerNativePINVOKE.new_GUIManager(), true) {
  }

  public bool Initialize(MainWindow mainWindow, DeviceType deviceType) {
    bool ret = EffekseerNativePINVOKE.GUIManager_Initialize(swigCPtr, MainWindow.getCPtr(mainWindow), (int)deviceType);
    return ret;
  }

  public void InitializeGUI(GraphicsDevice graphicsDevice) {
    EffekseerNativePINVOKE.GUIManager_InitializeGUI(swigCPtr, GraphicsDevice.getCPtr(graphicsDevice));
  }

  public void ResetGUIStyle() {
    EffekseerNativePINVOKE.GUIManager_ResetGUIStyle(swigCPtr);
  }

  public void SetTitle(string title) {
    EffekseerNativePINVOKE.GUIManager_SetTitle(swigCPtr, title);
  }

  public void SetWindowIcon(string iconPath) {
    EffekseerNativePINVOKE.GUIManager_SetWindowIcon(swigCPtr, iconPath);
  }

  public Vec2 GetSize() {
    Vec2 ret = new Vec2(EffekseerNativePINVOKE.GUIManager_GetSize(swigCPtr), true);
    return ret;
  }

  public void SetSize(int width, int height) {
    EffekseerNativePINVOKE.GUIManager_SetSize(swigCPtr, width, height);
  }

  public void Terminate() {
    EffekseerNativePINVOKE.GUIManager_Terminate(swigCPtr);
  }

  public bool DoEvents() {
    bool ret = EffekseerNativePINVOKE.GUIManager_DoEvents(swigCPtr);
    return ret;
  }

  public float GetDeltaSecond() {
    float ret = EffekseerNativePINVOKE.GUIManager_GetDeltaSecond(swigCPtr);
    return ret;
  }

  public void Present() {
    EffekseerNativePINVOKE.GUIManager_Present(swigCPtr);
  }

  public void Close() {
    EffekseerNativePINVOKE.GUIManager_Close(swigCPtr);
  }

  public bool IsWindowMaximized() {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsWindowMaximized(swigCPtr);
    return ret;
  }

  public void SetWindowMaximized(bool maximized) {
    EffekseerNativePINVOKE.GUIManager_SetWindowMaximized(swigCPtr, maximized);
  }

  public bool IsWindowMinimized() {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsWindowMinimized(swigCPtr);
    return ret;
  }

  public void SetWindowMinimized(bool minimized) {
    EffekseerNativePINVOKE.GUIManager_SetWindowMinimized(swigCPtr, minimized);
  }

  public Vec2 GetMousePosition() {
    Vec2 ret = new Vec2(EffekseerNativePINVOKE.GUIManager_GetMousePosition(swigCPtr), true);
    return ret;
  }

  public int GetMouseButton(int mouseButton) {
    int ret = EffekseerNativePINVOKE.GUIManager_GetMouseButton(swigCPtr, mouseButton);
    return ret;
  }

  public int GetMouseWheel() {
    int ret = EffekseerNativePINVOKE.GUIManager_GetMouseWheel(swigCPtr);
    return ret;
  }

  public void SetCallback(GUIManagerCallback callback) {
    EffekseerNativePINVOKE.GUIManager_SetCallback(swigCPtr, GUIManagerCallback.getCPtr(callback));
  }

  public void InvalidateFont() {
    EffekseerNativePINVOKE.GUIManager_InvalidateFont(swigCPtr);
  }

  public void ResetGUI() {
    EffekseerNativePINVOKE.GUIManager_ResetGUI(swigCPtr);
  }

  public void RenderGUI(bool isValid) {
    EffekseerNativePINVOKE.GUIManager_RenderGUI__SWIG_0(swigCPtr, isValid);
  }

  public void RenderGUI() {
    EffekseerNativePINVOKE.GUIManager_RenderGUI__SWIG_1(swigCPtr);
  }

  public System.IntPtr GetNativeHandle() { return EffekseerNativePINVOKE.GUIManager_GetNativeHandle(swigCPtr); }

  public string GetClipboardText() {
    string ret = System.Runtime.InteropServices.Marshal.PtrToStringUni(EffekseerNativePINVOKE.GUIManager_GetClipboardText(swigCPtr));
    return ret;
  }

  public void SetClipboardText(string text) {
    EffekseerNativePINVOKE.GUIManager_SetClipboardText(swigCPtr, text);
  }

  public bool Begin(string name, ref bool p_open) {
    bool ret = EffekseerNativePINVOKE.GUIManager_Begin(swigCPtr, name, ref p_open);
    return ret;
  }

  public void End() {
    EffekseerNativePINVOKE.GUIManager_End(swigCPtr);
  }

  public bool BeginChild(string str_id, Vec2 size_arg, bool border, WindowFlags extra_flags) {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginChild__SWIG_0(swigCPtr, str_id, Vec2.getCPtr(size_arg), border, (int)extra_flags);
    if (EffekseerNativePINVOKE.SWIGPendingException.Pending) throw EffekseerNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool BeginChild(string str_id, Vec2 size_arg, bool border) {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginChild__SWIG_1(swigCPtr, str_id, Vec2.getCPtr(size_arg), border);
    if (EffekseerNativePINVOKE.SWIGPendingException.Pending) throw EffekseerNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool BeginChild(string str_id, Vec2 size_arg) {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginChild__SWIG_2(swigCPtr, str_id, Vec2.getCPtr(size_arg));
    if (EffekseerNativePINVOKE.SWIGPendingException.Pending) throw EffekseerNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool BeginChild(string str_id) {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginChild__SWIG_3(swigCPtr, str_id);
    return ret;
  }

  public void EndChild() {
    EffekseerNativePINVOKE.GUIManager_EndChild(swigCPtr);
  }

  public Vec2 GetWindowPos() {
    Vec2 ret = new Vec2(EffekseerNativePINVOKE.GUIManager_GetWindowPos(swigCPtr), true);
    return ret;
  }

  public Vec2 GetWindowSize() {
    Vec2 ret = new Vec2(EffekseerNativePINVOKE.GUIManager_GetWindowSize(swigCPtr), true);
    return ret;
  }

  public Vec2 GetContentRegionAvail() {
    Vec2 ret = new Vec2(EffekseerNativePINVOKE.GUIManager_GetContentRegionAvail(swigCPtr), true);
    return ret;
  }

  public void SetNextWindowPos(Vec2 pos, Cond cond, Vec2 pivot) {
    EffekseerNativePINVOKE.GUIManager_SetNextWindowPos(swigCPtr, Vec2.getCPtr(pos), (int)cond, Vec2.getCPtr(pivot));
    if (EffekseerNativePINVOKE.SWIGPendingException.Pending) throw EffekseerNativePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetNextWindowSize(float size_x, float size_y, Cond cond) {
    EffekseerNativePINVOKE.GUIManager_SetNextWindowSize(swigCPtr, size_x, size_y, (int)cond);
  }

  public void PushStyleColor(ImGuiColFlags idx, uint col) {
    EffekseerNativePINVOKE.GUIManager_PushStyleColor(swigCPtr, (int)idx, col);
  }

  public void PopStyleColor(int count) {
    EffekseerNativePINVOKE.GUIManager_PopStyleColor__SWIG_0(swigCPtr, count);
  }

  public void PopStyleColor() {
    EffekseerNativePINVOKE.GUIManager_PopStyleColor__SWIG_1(swigCPtr);
  }

  public void PushStyleVar(ImGuiStyleVarFlags idx, float val) {
    EffekseerNativePINVOKE.GUIManager_PushStyleVar__SWIG_0(swigCPtr, (int)idx, val);
  }

  public void PushStyleVar(ImGuiStyleVarFlags idx, Vec2 val) {
    EffekseerNativePINVOKE.GUIManager_PushStyleVar__SWIG_1(swigCPtr, (int)idx, Vec2.getCPtr(val));
    if (EffekseerNativePINVOKE.SWIGPendingException.Pending) throw EffekseerNativePINVOKE.SWIGPendingException.Retrieve();
  }

  public void PopStyleVar(int count) {
    EffekseerNativePINVOKE.GUIManager_PopStyleVar__SWIG_0(swigCPtr, count);
  }

  public void PopStyleVar() {
    EffekseerNativePINVOKE.GUIManager_PopStyleVar__SWIG_1(swigCPtr);
  }

  public float GetStyleVar(ImGuiStyleVarFlags idx) {
    float ret = EffekseerNativePINVOKE.GUIManager_GetStyleVar(swigCPtr, (int)idx);
    return ret;
  }

  public Vec2 GetStyleVar2(ImGuiStyleVarFlags idx) {
    Vec2 ret = new Vec2(EffekseerNativePINVOKE.GUIManager_GetStyleVar2(swigCPtr, (int)idx), true);
    return ret;
  }

  public void PushItemWidth(float item_width) {
    EffekseerNativePINVOKE.GUIManager_PushItemWidth(swigCPtr, item_width);
  }

  public void PopItemWidth() {
    EffekseerNativePINVOKE.GUIManager_PopItemWidth(swigCPtr);
  }

  public void Separator() {
    EffekseerNativePINVOKE.GUIManager_Separator(swigCPtr);
  }

  public void Indent(float indent_w) {
    EffekseerNativePINVOKE.GUIManager_Indent(swigCPtr, indent_w);
  }

  public void Spacing() {
    EffekseerNativePINVOKE.GUIManager_Spacing(swigCPtr);
  }

  public void Dummy(Vector2I size) {
    EffekseerNativePINVOKE.GUIManager_Dummy(swigCPtr, Vector2I.getCPtr(size));
    if (EffekseerNativePINVOKE.SWIGPendingException.Pending) throw EffekseerNativePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SameLine(float offset_from_start_x, float spacing) {
    EffekseerNativePINVOKE.GUIManager_SameLine__SWIG_0(swigCPtr, offset_from_start_x, spacing);
  }

  public void SameLine(float offset_from_start_x) {
    EffekseerNativePINVOKE.GUIManager_SameLine__SWIG_1(swigCPtr, offset_from_start_x);
  }

  public void SameLine() {
    EffekseerNativePINVOKE.GUIManager_SameLine__SWIG_2(swigCPtr);
  }

  public void BeginDisabled(bool disabled) {
    EffekseerNativePINVOKE.GUIManager_BeginDisabled(swigCPtr, disabled);
  }

  public void EndDisabled() {
    EffekseerNativePINVOKE.GUIManager_EndDisabled(swigCPtr);
  }

  public void AddRectFilled(float minX, float minY, float maxX, float maxY, uint color, float rounding, int flags) {
    EffekseerNativePINVOKE.GUIManager_AddRectFilled(swigCPtr, minX, minY, maxX, maxY, color, rounding, flags);
  }

  public void BeginGroup() {
    EffekseerNativePINVOKE.GUIManager_BeginGroup(swigCPtr);
  }

  public void EndGroup() {
    EffekseerNativePINVOKE.GUIManager_EndGroup(swigCPtr);
  }

  public void AlignTextToFramePadding() {
    EffekseerNativePINVOKE.GUIManager_AlignTextToFramePadding(swigCPtr);
  }

  public void SetNextItemWidth(float width) {
    EffekseerNativePINVOKE.GUIManager_SetNextItemWidth(swigCPtr, width);
  }

  public void SetCursorPosX(float x) {
    EffekseerNativePINVOKE.GUIManager_SetCursorPosX(swigCPtr, x);
  }

  public void SetCursorPosY(float y) {
    EffekseerNativePINVOKE.GUIManager_SetCursorPosY(swigCPtr, y);
  }

  public float GetCursorPosX() {
    float ret = EffekseerNativePINVOKE.GUIManager_GetCursorPosX(swigCPtr);
    return ret;
  }

  public float GetCursorPosY() {
    float ret = EffekseerNativePINVOKE.GUIManager_GetCursorPosY(swigCPtr);
    return ret;
  }

  public float GetCursorScreenPosX() {
    float ret = EffekseerNativePINVOKE.GUIManager_GetCursorScreenPosX(swigCPtr);
    return ret;
  }

  public float GetCursorScreenPosY() {
    float ret = EffekseerNativePINVOKE.GUIManager_GetCursorScreenPosY(swigCPtr);
    return ret;
  }

  public float GetItemRectMinX() {
    float ret = EffekseerNativePINVOKE.GUIManager_GetItemRectMinX(swigCPtr);
    return ret;
  }

  public float GetItemRectMinY() {
    float ret = EffekseerNativePINVOKE.GUIManager_GetItemRectMinY(swigCPtr);
    return ret;
  }

  public float GetItemRectMaxX() {
    float ret = EffekseerNativePINVOKE.GUIManager_GetItemRectMaxX(swigCPtr);
    return ret;
  }

  public float GetItemRectMaxY() {
    float ret = EffekseerNativePINVOKE.GUIManager_GetItemRectMaxY(swigCPtr);
    return ret;
  }

  public float GetItemRectSizeX() {
    float ret = EffekseerNativePINVOKE.GUIManager_GetItemRectSizeX(swigCPtr);
    return ret;
  }

  public float GetItemRectSizeY() {
    float ret = EffekseerNativePINVOKE.GUIManager_GetItemRectSizeY(swigCPtr);
    return ret;
  }

  public Vec2 GetItemSpacing() {
    Vec2 ret = new Vec2(EffekseerNativePINVOKE.GUIManager_GetItemSpacing(swigCPtr), true);
    return ret;
  }

  public float GetTextLineHeight() {
    float ret = EffekseerNativePINVOKE.GUIManager_GetTextLineHeight(swigCPtr);
    return ret;
  }

  public float GetTextLineHeightWithSpacing() {
    float ret = EffekseerNativePINVOKE.GUIManager_GetTextLineHeightWithSpacing(swigCPtr);
    return ret;
  }

  public float GetFrameHeight() {
    float ret = EffekseerNativePINVOKE.GUIManager_GetFrameHeight(swigCPtr);
    return ret;
  }

  public float GetFrameHeightWithSpacing() {
    float ret = EffekseerNativePINVOKE.GUIManager_GetFrameHeightWithSpacing(swigCPtr);
    return ret;
  }

  public float GetDpiScale() {
    float ret = EffekseerNativePINVOKE.GUIManager_GetDpiScale(swigCPtr);
    return ret;
  }

  public int GetItemID() {
    int ret = EffekseerNativePINVOKE.GUIManager_GetItemID(swigCPtr);
    return ret;
  }

  public void SetFocusID(int id) {
    EffekseerNativePINVOKE.GUIManager_SetFocusID(swigCPtr, id);
  }

  public float GetScrollX() {
    float ret = EffekseerNativePINVOKE.GUIManager_GetScrollX(swigCPtr);
    return ret;
  }

  public float GetScrollY() {
    float ret = EffekseerNativePINVOKE.GUIManager_GetScrollY(swigCPtr);
    return ret;
  }

  public void SetScrollX(float scroll_x) {
    EffekseerNativePINVOKE.GUIManager_SetScrollX(swigCPtr, scroll_x);
  }

  public void SetScrollY(float scroll_y) {
    EffekseerNativePINVOKE.GUIManager_SetScrollY(swigCPtr, scroll_y);
  }

  public float GetScrollMaxX() {
    float ret = EffekseerNativePINVOKE.GUIManager_GetScrollMaxX(swigCPtr);
    return ret;
  }

  public float GetScrollMaxY() {
    float ret = EffekseerNativePINVOKE.GUIManager_GetScrollMaxY(swigCPtr);
    return ret;
  }

  public void ScrollToRect(Vec2 rect_min, Vec2 rect_max) {
    EffekseerNativePINVOKE.GUIManager_ScrollToRect(swigCPtr, Vec2.getCPtr(rect_min), Vec2.getCPtr(rect_max));
    if (EffekseerNativePINVOKE.SWIGPendingException.Pending) throw EffekseerNativePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Columns(int count, string id, bool border) {
    EffekseerNativePINVOKE.GUIManager_Columns__SWIG_0(swigCPtr, count, id, border);
  }

  public void Columns(int count, string id) {
    EffekseerNativePINVOKE.GUIManager_Columns__SWIG_1(swigCPtr, count, id);
  }

  public void Columns(int count) {
    EffekseerNativePINVOKE.GUIManager_Columns__SWIG_2(swigCPtr, count);
  }

  public void Columns() {
    EffekseerNativePINVOKE.GUIManager_Columns__SWIG_3(swigCPtr);
  }

  public void NextColumn() {
    EffekseerNativePINVOKE.GUIManager_NextColumn(swigCPtr);
  }

  public float GetColumnWidth(int column_index) {
    float ret = EffekseerNativePINVOKE.GUIManager_GetColumnWidth__SWIG_0(swigCPtr, column_index);
    return ret;
  }

  public float GetColumnWidth() {
    float ret = EffekseerNativePINVOKE.GUIManager_GetColumnWidth__SWIG_1(swigCPtr);
    return ret;
  }

  public void SetColumnWidth(int column_index, float width) {
    EffekseerNativePINVOKE.GUIManager_SetColumnWidth(swigCPtr, column_index, width);
  }

  public float GetColumnOffset(int column_index) {
    float ret = EffekseerNativePINVOKE.GUIManager_GetColumnOffset__SWIG_0(swigCPtr, column_index);
    return ret;
  }

  public float GetColumnOffset() {
    float ret = EffekseerNativePINVOKE.GUIManager_GetColumnOffset__SWIG_1(swigCPtr);
    return ret;
  }

  public void SetColumnOffset(int column_index, float offset_x) {
    EffekseerNativePINVOKE.GUIManager_SetColumnOffset(swigCPtr, column_index, offset_x);
  }

  public void Text(string text) {
    EffekseerNativePINVOKE.GUIManager_Text(swigCPtr, text);
  }

  public void TextWrapped(string text) {
    EffekseerNativePINVOKE.GUIManager_TextWrapped(swigCPtr, text);
  }

  public Vec2 CalcTextSize(string text) {
    Vec2 ret = new Vec2(EffekseerNativePINVOKE.GUIManager_CalcTextSize(swigCPtr, text), true);
    return ret;
  }

  public bool Button(string label, float size_x, float size_y) {
    bool ret = EffekseerNativePINVOKE.GUIManager_Button__SWIG_0(swigCPtr, label, size_x, size_y);
    return ret;
  }

  public bool Button(string label, float size_x) {
    bool ret = EffekseerNativePINVOKE.GUIManager_Button__SWIG_1(swigCPtr, label, size_x);
    return ret;
  }

  public bool Button(string label) {
    bool ret = EffekseerNativePINVOKE.GUIManager_Button__SWIG_2(swigCPtr, label);
    return ret;
  }

  public void ImageData(Image user_texture_id, float x, float y, float uv0_x, float uv0_y, float uv1_x, float uv1_y) {
    EffekseerNativePINVOKE.GUIManager_ImageData__SWIG_0(swigCPtr, Image.getCPtr(user_texture_id), x, y, uv0_x, uv0_y, uv1_x, uv1_y);
  }

  public void ImageData(Image user_texture_id, float x, float y, float uv0_x, float uv0_y, float uv1_x) {
    EffekseerNativePINVOKE.GUIManager_ImageData__SWIG_1(swigCPtr, Image.getCPtr(user_texture_id), x, y, uv0_x, uv0_y, uv1_x);
  }

  public void ImageData(Image user_texture_id, float x, float y, float uv0_x, float uv0_y) {
    EffekseerNativePINVOKE.GUIManager_ImageData__SWIG_2(swigCPtr, Image.getCPtr(user_texture_id), x, y, uv0_x, uv0_y);
  }

  public void ImageData(Image user_texture_id, float x, float y, float uv0_x) {
    EffekseerNativePINVOKE.GUIManager_ImageData__SWIG_3(swigCPtr, Image.getCPtr(user_texture_id), x, y, uv0_x);
  }

  public void ImageData(Image user_texture_id, float x, float y) {
    EffekseerNativePINVOKE.GUIManager_ImageData__SWIG_4(swigCPtr, Image.getCPtr(user_texture_id), x, y);
  }

  public bool ImageButton(Image user_texture_id, float x, float y) {
    bool ret = EffekseerNativePINVOKE.GUIManager_ImageButton(swigCPtr, Image.getCPtr(user_texture_id), x, y);
    return ret;
  }

  public bool ImageButtonOriginal(Image user_texture_id, float x, float y) {
    bool ret = EffekseerNativePINVOKE.GUIManager_ImageButtonOriginal(swigCPtr, Image.getCPtr(user_texture_id), x, y);
    return ret;
  }

  public bool IconButton(string icon, float size) {
    bool ret = EffekseerNativePINVOKE.GUIManager_IconButton__SWIG_0(swigCPtr, icon, size);
    return ret;
  }

  public bool IconButton(string icon) {
    bool ret = EffekseerNativePINVOKE.GUIManager_IconButton__SWIG_1(swigCPtr, icon);
    return ret;
  }

  public bool Checkbox(string label, bool[] v) {
    bool ret = EffekseerNativePINVOKE.GUIManager_Checkbox(swigCPtr, label, v);
    return ret;
  }

  public bool RadioButton(string label, bool active) {
    bool ret = EffekseerNativePINVOKE.GUIManager_RadioButton(swigCPtr, label, active);
    return ret;
  }

  public bool ToggleButton(string label, ref bool p_checked) {
    bool ret = EffekseerNativePINVOKE.GUIManager_ToggleButton(swigCPtr, label, ref p_checked);
    return ret;
  }

  public bool InputInt(string label, int[] v, int step, int step_fast) {
    bool ret = EffekseerNativePINVOKE.GUIManager_InputInt__SWIG_0(swigCPtr, label, v, step, step_fast);
    return ret;
  }

  public bool InputInt(string label, int[] v, int step) {
    bool ret = EffekseerNativePINVOKE.GUIManager_InputInt__SWIG_1(swigCPtr, label, v, step);
    return ret;
  }

  public bool InputInt(string label, int[] v) {
    bool ret = EffekseerNativePINVOKE.GUIManager_InputInt__SWIG_2(swigCPtr, label, v);
    return ret;
  }

  public bool SliderInt(string label, int[] v, int v_min, int v_max) {
    bool ret = EffekseerNativePINVOKE.GUIManager_SliderInt(swigCPtr, label, v, v_min, v_max);
    return ret;
  }

  public void ProgressBar(float fraction, Vec2 size) {
    EffekseerNativePINVOKE.GUIManager_ProgressBar(swigCPtr, fraction, Vec2.getCPtr(size));
    if (EffekseerNativePINVOKE.SWIGPendingException.Pending) throw EffekseerNativePINVOKE.SWIGPendingException.Retrieve();
  }

  public bool BeginCombo(string label, string preview_value, ComboFlags flags, Image user_texture_id) {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginCombo__SWIG_0(swigCPtr, label, preview_value, (int)flags, Image.getCPtr(user_texture_id));
    return ret;
  }

  public bool BeginCombo(string label, string preview_value, ComboFlags flags) {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginCombo__SWIG_1(swigCPtr, label, preview_value, (int)flags);
    return ret;
  }

  public void EndCombo() {
    EffekseerNativePINVOKE.GUIManager_EndCombo(swigCPtr);
  }

  public bool DragFloat(string label, float[] v, float v_speed, float v_min, float v_max, string display_format, float power) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat__SWIG_0(swigCPtr, label, v, v_speed, v_min, v_max, display_format, power);
    return ret;
  }

  public bool DragFloat(string label, float[] v, float v_speed, float v_min, float v_max, string display_format) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat__SWIG_1(swigCPtr, label, v, v_speed, v_min, v_max, display_format);
    return ret;
  }

  public bool DragFloat(string label, float[] v, float v_speed, float v_min, float v_max) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat__SWIG_2(swigCPtr, label, v, v_speed, v_min, v_max);
    return ret;
  }

  public bool DragFloat(string label, float[] v, float v_speed, float v_min) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat__SWIG_3(swigCPtr, label, v, v_speed, v_min);
    return ret;
  }

  public bool DragFloat(string label, float[] v, float v_speed) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat__SWIG_4(swigCPtr, label, v, v_speed);
    return ret;
  }

  public bool DragFloat(string label, float[] v) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat__SWIG_5(swigCPtr, label, v);
    return ret;
  }

  public bool DragFloat2(string label, float[] v, float v_speed, float v_min, float v_max, string display_format, float power) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat2__SWIG_0(swigCPtr, label, v, v_speed, v_min, v_max, display_format, power);
    return ret;
  }

  public bool DragFloat2(string label, float[] v, float v_speed, float v_min, float v_max, string display_format) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat2__SWIG_1(swigCPtr, label, v, v_speed, v_min, v_max, display_format);
    return ret;
  }

  public bool DragFloat2(string label, float[] v, float v_speed, float v_min, float v_max) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat2__SWIG_2(swigCPtr, label, v, v_speed, v_min, v_max);
    return ret;
  }

  public bool DragFloat2(string label, float[] v, float v_speed, float v_min) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat2__SWIG_3(swigCPtr, label, v, v_speed, v_min);
    return ret;
  }

  public bool DragFloat2(string label, float[] v, float v_speed) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat2__SWIG_4(swigCPtr, label, v, v_speed);
    return ret;
  }

  public bool DragFloat2(string label, float[] v) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat2__SWIG_5(swigCPtr, label, v);
    return ret;
  }

  public bool DragFloat3(string label, float[] v, float v_speed, float v_min, float v_max, string display_format, float power) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat3__SWIG_0(swigCPtr, label, v, v_speed, v_min, v_max, display_format, power);
    return ret;
  }

  public bool DragFloat3(string label, float[] v, float v_speed, float v_min, float v_max, string display_format) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat3__SWIG_1(swigCPtr, label, v, v_speed, v_min, v_max, display_format);
    return ret;
  }

  public bool DragFloat3(string label, float[] v, float v_speed, float v_min, float v_max) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat3__SWIG_2(swigCPtr, label, v, v_speed, v_min, v_max);
    return ret;
  }

  public bool DragFloat3(string label, float[] v, float v_speed, float v_min) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat3__SWIG_3(swigCPtr, label, v, v_speed, v_min);
    return ret;
  }

  public bool DragFloat3(string label, float[] v, float v_speed) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat3__SWIG_4(swigCPtr, label, v, v_speed);
    return ret;
  }

  public bool DragFloat3(string label, float[] v) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat3__SWIG_5(swigCPtr, label, v);
    return ret;
  }

  public bool DragFloat4(string label, float[] v, float v_speed, float v_min, float v_max, string display_format, float power) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat4__SWIG_0(swigCPtr, label, v, v_speed, v_min, v_max, display_format, power);
    return ret;
  }

  public bool DragFloat4(string label, float[] v, float v_speed, float v_min, float v_max, string display_format) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat4__SWIG_1(swigCPtr, label, v, v_speed, v_min, v_max, display_format);
    return ret;
  }

  public bool DragFloat4(string label, float[] v, float v_speed, float v_min, float v_max) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat4__SWIG_2(swigCPtr, label, v, v_speed, v_min, v_max);
    return ret;
  }

  public bool DragFloat4(string label, float[] v, float v_speed, float v_min) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat4__SWIG_3(swigCPtr, label, v, v_speed, v_min);
    return ret;
  }

  public bool DragFloat4(string label, float[] v, float v_speed) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat4__SWIG_4(swigCPtr, label, v, v_speed);
    return ret;
  }

  public bool DragFloat4(string label, float[] v) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat4__SWIG_5(swigCPtr, label, v);
    return ret;
  }

  public bool DragFloatRange2(string label, float[] v_current_min, float[] v_current_max, float v_speed, float v_min, float v_max, string display_format, string display_format_max, float power) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloatRange2__SWIG_0(swigCPtr, label, v_current_min, v_current_max, v_speed, v_min, v_max, display_format, display_format_max, power);
    return ret;
  }

  public bool DragFloatRange2(string label, float[] v_current_min, float[] v_current_max, float v_speed, float v_min, float v_max, string display_format, string display_format_max) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloatRange2__SWIG_1(swigCPtr, label, v_current_min, v_current_max, v_speed, v_min, v_max, display_format, display_format_max);
    return ret;
  }

  public bool DragFloatRange2(string label, float[] v_current_min, float[] v_current_max, float v_speed, float v_min, float v_max, string display_format) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloatRange2__SWIG_2(swigCPtr, label, v_current_min, v_current_max, v_speed, v_min, v_max, display_format);
    return ret;
  }

  public bool DragFloatRange2(string label, float[] v_current_min, float[] v_current_max, float v_speed, float v_min, float v_max) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloatRange2__SWIG_3(swigCPtr, label, v_current_min, v_current_max, v_speed, v_min, v_max);
    return ret;
  }

  public bool DragFloatRange2(string label, float[] v_current_min, float[] v_current_max, float v_speed, float v_min) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloatRange2__SWIG_4(swigCPtr, label, v_current_min, v_current_max, v_speed, v_min);
    return ret;
  }

  public bool DragFloatRange2(string label, float[] v_current_min, float[] v_current_max, float v_speed) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloatRange2__SWIG_5(swigCPtr, label, v_current_min, v_current_max, v_speed);
    return ret;
  }

  public bool DragFloatRange2(string label, float[] v_current_min, float[] v_current_max) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloatRange2__SWIG_6(swigCPtr, label, v_current_min, v_current_max);
    return ret;
  }

  public bool DragInt(string label, int[] v, float v_speed, int v_min, int v_max, string display_format) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt__SWIG_0(swigCPtr, label, v, v_speed, v_min, v_max, display_format);
    return ret;
  }

  public bool DragInt(string label, int[] v, float v_speed, int v_min, int v_max) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt__SWIG_1(swigCPtr, label, v, v_speed, v_min, v_max);
    return ret;
  }

  public bool DragInt(string label, int[] v, float v_speed, int v_min) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt__SWIG_2(swigCPtr, label, v, v_speed, v_min);
    return ret;
  }

  public bool DragInt(string label, int[] v, float v_speed) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt__SWIG_3(swigCPtr, label, v, v_speed);
    return ret;
  }

  public bool DragInt(string label, int[] v) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt__SWIG_4(swigCPtr, label, v);
    return ret;
  }

  public bool DragInt2(string label, int[] v, float v_speed, int v_min, int v_max, string display_format) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt2__SWIG_0(swigCPtr, label, v, v_speed, v_min, v_max, display_format);
    return ret;
  }

  public bool DragInt2(string label, int[] v, float v_speed, int v_min, int v_max) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt2__SWIG_1(swigCPtr, label, v, v_speed, v_min, v_max);
    return ret;
  }

  public bool DragInt2(string label, int[] v, float v_speed, int v_min) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt2__SWIG_2(swigCPtr, label, v, v_speed, v_min);
    return ret;
  }

  public bool DragInt2(string label, int[] v, float v_speed) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt2__SWIG_3(swigCPtr, label, v, v_speed);
    return ret;
  }

  public bool DragInt2(string label, int[] v) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt2__SWIG_4(swigCPtr, label, v);
    return ret;
  }

  public bool DragInt3(string label, int[] v, float v_speed, int v_min, int v_max, string display_format) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt3__SWIG_0(swigCPtr, label, v, v_speed, v_min, v_max, display_format);
    return ret;
  }

  public bool DragInt3(string label, int[] v, float v_speed, int v_min, int v_max) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt3__SWIG_1(swigCPtr, label, v, v_speed, v_min, v_max);
    return ret;
  }

  public bool DragInt3(string label, int[] v, float v_speed, int v_min) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt3__SWIG_2(swigCPtr, label, v, v_speed, v_min);
    return ret;
  }

  public bool DragInt3(string label, int[] v, float v_speed) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt3__SWIG_3(swigCPtr, label, v, v_speed);
    return ret;
  }

  public bool DragInt3(string label, int[] v) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt3__SWIG_4(swigCPtr, label, v);
    return ret;
  }

  public bool DragInt4(string label, int[] v, float v_speed, int v_min, int v_max, string display_format) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt4__SWIG_0(swigCPtr, label, v, v_speed, v_min, v_max, display_format);
    return ret;
  }

  public bool DragInt4(string label, int[] v, float v_speed, int v_min, int v_max) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt4__SWIG_1(swigCPtr, label, v, v_speed, v_min, v_max);
    return ret;
  }

  public bool DragInt4(string label, int[] v, float v_speed, int v_min) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt4__SWIG_2(swigCPtr, label, v, v_speed, v_min);
    return ret;
  }

  public bool DragInt4(string label, int[] v, float v_speed) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt4__SWIG_3(swigCPtr, label, v, v_speed);
    return ret;
  }

  public bool DragInt4(string label, int[] v) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt4__SWIG_4(swigCPtr, label, v);
    return ret;
  }

  public bool DragIntRange2(string label, int[] v_current_min, int[] v_current_max, float v_speed, int v_min, int v_max, string display_format, string display_format_max) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragIntRange2__SWIG_0(swigCPtr, label, v_current_min, v_current_max, v_speed, v_min, v_max, display_format, display_format_max);
    return ret;
  }

  public bool DragIntRange2(string label, int[] v_current_min, int[] v_current_max, float v_speed, int v_min, int v_max, string display_format) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragIntRange2__SWIG_1(swigCPtr, label, v_current_min, v_current_max, v_speed, v_min, v_max, display_format);
    return ret;
  }

  public bool DragIntRange2(string label, int[] v_current_min, int[] v_current_max, float v_speed, int v_min, int v_max) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragIntRange2__SWIG_2(swigCPtr, label, v_current_min, v_current_max, v_speed, v_min, v_max);
    return ret;
  }

  public bool DragIntRange2(string label, int[] v_current_min, int[] v_current_max, float v_speed, int v_min) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragIntRange2__SWIG_3(swigCPtr, label, v_current_min, v_current_max, v_speed, v_min);
    return ret;
  }

  public bool DragIntRange2(string label, int[] v_current_min, int[] v_current_max, float v_speed) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragIntRange2__SWIG_4(swigCPtr, label, v_current_min, v_current_max, v_speed);
    return ret;
  }

  public bool DragIntRange2(string label, int[] v_current_min, int[] v_current_max) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragIntRange2__SWIG_5(swigCPtr, label, v_current_min, v_current_max);
    return ret;
  }

  public bool DragFloat1EfkEx(string label, float[] v, float v_speed, float v_min, float v_max, string display_format1, float power) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat1EfkEx__SWIG_0(swigCPtr, label, v, v_speed, v_min, v_max, display_format1, power);
    return ret;
  }

  public bool DragFloat1EfkEx(string label, float[] v, float v_speed, float v_min, float v_max, string display_format1) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat1EfkEx__SWIG_1(swigCPtr, label, v, v_speed, v_min, v_max, display_format1);
    return ret;
  }

  public bool DragFloat1EfkEx(string label, float[] v, float v_speed, float v_min, float v_max) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat1EfkEx__SWIG_2(swigCPtr, label, v, v_speed, v_min, v_max);
    return ret;
  }

  public bool DragFloat1EfkEx(string label, float[] v, float v_speed, float v_min) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat1EfkEx__SWIG_3(swigCPtr, label, v, v_speed, v_min);
    return ret;
  }

  public bool DragFloat1EfkEx(string label, float[] v, float v_speed) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat1EfkEx__SWIG_4(swigCPtr, label, v, v_speed);
    return ret;
  }

  public bool DragFloat1EfkEx(string label, float[] v) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat1EfkEx__SWIG_5(swigCPtr, label, v);
    return ret;
  }

  public bool DragFloat2EfkEx(string label, float[] v, float v_speed, float v_min1, float v_max1, float v_min2, float v_max2, string display_format1, string display_format2, float power) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat2EfkEx__SWIG_0(swigCPtr, label, v, v_speed, v_min1, v_max1, v_min2, v_max2, display_format1, display_format2, power);
    return ret;
  }

  public bool DragFloat2EfkEx(string label, float[] v, float v_speed, float v_min1, float v_max1, float v_min2, float v_max2, string display_format1, string display_format2) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat2EfkEx__SWIG_1(swigCPtr, label, v, v_speed, v_min1, v_max1, v_min2, v_max2, display_format1, display_format2);
    return ret;
  }

  public bool DragFloat2EfkEx(string label, float[] v, float v_speed, float v_min1, float v_max1, float v_min2, float v_max2, string display_format1) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat2EfkEx__SWIG_2(swigCPtr, label, v, v_speed, v_min1, v_max1, v_min2, v_max2, display_format1);
    return ret;
  }

  public bool DragFloat2EfkEx(string label, float[] v, float v_speed, float v_min1, float v_max1, float v_min2, float v_max2) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat2EfkEx__SWIG_3(swigCPtr, label, v, v_speed, v_min1, v_max1, v_min2, v_max2);
    return ret;
  }

  public bool DragFloat2EfkEx(string label, float[] v, float v_speed, float v_min1, float v_max1, float v_min2) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat2EfkEx__SWIG_4(swigCPtr, label, v, v_speed, v_min1, v_max1, v_min2);
    return ret;
  }

  public bool DragFloat2EfkEx(string label, float[] v, float v_speed, float v_min1, float v_max1) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat2EfkEx__SWIG_5(swigCPtr, label, v, v_speed, v_min1, v_max1);
    return ret;
  }

  public bool DragFloat2EfkEx(string label, float[] v, float v_speed, float v_min1) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat2EfkEx__SWIG_6(swigCPtr, label, v, v_speed, v_min1);
    return ret;
  }

  public bool DragFloat2EfkEx(string label, float[] v, float v_speed) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat2EfkEx__SWIG_7(swigCPtr, label, v, v_speed);
    return ret;
  }

  public bool DragFloat2EfkEx(string label, float[] v) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat2EfkEx__SWIG_8(swigCPtr, label, v);
    return ret;
  }

  public bool DragFloat3EfkEx(string label, float[] v, float v_speed, float v_min1, float v_max1, float v_min2, float v_max2, float v_min3, float v_max3, string display_format1, string display_format2, string display_format3, float power) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat3EfkEx__SWIG_0(swigCPtr, label, v, v_speed, v_min1, v_max1, v_min2, v_max2, v_min3, v_max3, display_format1, display_format2, display_format3, power);
    return ret;
  }

  public bool DragFloat3EfkEx(string label, float[] v, float v_speed, float v_min1, float v_max1, float v_min2, float v_max2, float v_min3, float v_max3, string display_format1, string display_format2, string display_format3) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat3EfkEx__SWIG_1(swigCPtr, label, v, v_speed, v_min1, v_max1, v_min2, v_max2, v_min3, v_max3, display_format1, display_format2, display_format3);
    return ret;
  }

  public bool DragFloat3EfkEx(string label, float[] v, float v_speed, float v_min1, float v_max1, float v_min2, float v_max2, float v_min3, float v_max3, string display_format1, string display_format2) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat3EfkEx__SWIG_2(swigCPtr, label, v, v_speed, v_min1, v_max1, v_min2, v_max2, v_min3, v_max3, display_format1, display_format2);
    return ret;
  }

  public bool DragFloat3EfkEx(string label, float[] v, float v_speed, float v_min1, float v_max1, float v_min2, float v_max2, float v_min3, float v_max3, string display_format1) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat3EfkEx__SWIG_3(swigCPtr, label, v, v_speed, v_min1, v_max1, v_min2, v_max2, v_min3, v_max3, display_format1);
    return ret;
  }

  public bool DragFloat3EfkEx(string label, float[] v, float v_speed, float v_min1, float v_max1, float v_min2, float v_max2, float v_min3, float v_max3) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat3EfkEx__SWIG_4(swigCPtr, label, v, v_speed, v_min1, v_max1, v_min2, v_max2, v_min3, v_max3);
    return ret;
  }

  public bool DragFloat3EfkEx(string label, float[] v, float v_speed, float v_min1, float v_max1, float v_min2, float v_max2, float v_min3) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat3EfkEx__SWIG_5(swigCPtr, label, v, v_speed, v_min1, v_max1, v_min2, v_max2, v_min3);
    return ret;
  }

  public bool DragFloat3EfkEx(string label, float[] v, float v_speed, float v_min1, float v_max1, float v_min2, float v_max2) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat3EfkEx__SWIG_6(swigCPtr, label, v, v_speed, v_min1, v_max1, v_min2, v_max2);
    return ret;
  }

  public bool DragFloat3EfkEx(string label, float[] v, float v_speed, float v_min1, float v_max1, float v_min2) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat3EfkEx__SWIG_7(swigCPtr, label, v, v_speed, v_min1, v_max1, v_min2);
    return ret;
  }

  public bool DragFloat3EfkEx(string label, float[] v, float v_speed, float v_min1, float v_max1) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat3EfkEx__SWIG_8(swigCPtr, label, v, v_speed, v_min1, v_max1);
    return ret;
  }

  public bool DragFloat3EfkEx(string label, float[] v, float v_speed, float v_min1) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat3EfkEx__SWIG_9(swigCPtr, label, v, v_speed, v_min1);
    return ret;
  }

  public bool DragFloat3EfkEx(string label, float[] v, float v_speed) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat3EfkEx__SWIG_10(swigCPtr, label, v, v_speed);
    return ret;
  }

  public bool DragFloat3EfkEx(string label, float[] v) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragFloat3EfkEx__SWIG_11(swigCPtr, label, v);
    return ret;
  }

  public bool DragInt2EfkEx(string label, int[] v, int v_speed, int v_min1, int v_max1, int v_min2, int v_max2, string display_format1, string display_format2) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt2EfkEx__SWIG_0(swigCPtr, label, v, v_speed, v_min1, v_max1, v_min2, v_max2, display_format1, display_format2);
    return ret;
  }

  public bool DragInt2EfkEx(string label, int[] v, int v_speed, int v_min1, int v_max1, int v_min2, int v_max2, string display_format1) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt2EfkEx__SWIG_1(swigCPtr, label, v, v_speed, v_min1, v_max1, v_min2, v_max2, display_format1);
    return ret;
  }

  public bool DragInt2EfkEx(string label, int[] v, int v_speed, int v_min1, int v_max1, int v_min2, int v_max2) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt2EfkEx__SWIG_2(swigCPtr, label, v, v_speed, v_min1, v_max1, v_min2, v_max2);
    return ret;
  }

  public bool DragInt2EfkEx(string label, int[] v, int v_speed, int v_min1, int v_max1, int v_min2) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt2EfkEx__SWIG_3(swigCPtr, label, v, v_speed, v_min1, v_max1, v_min2);
    return ret;
  }

  public bool DragInt2EfkEx(string label, int[] v, int v_speed, int v_min1, int v_max1) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt2EfkEx__SWIG_4(swigCPtr, label, v, v_speed, v_min1, v_max1);
    return ret;
  }

  public bool DragInt2EfkEx(string label, int[] v, int v_speed, int v_min1) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt2EfkEx__SWIG_5(swigCPtr, label, v, v_speed, v_min1);
    return ret;
  }

  public bool DragInt2EfkEx(string label, int[] v, int v_speed) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt2EfkEx__SWIG_6(swigCPtr, label, v, v_speed);
    return ret;
  }

  public bool DragInt2EfkEx(string label, int[] v) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt2EfkEx__SWIG_7(swigCPtr, label, v);
    return ret;
  }

  public bool InputText(string label, string text, InputTextFlags flags) {
    bool ret = EffekseerNativePINVOKE.GUIManager_InputText__SWIG_0(swigCPtr, label, text, (int)flags);
    return ret;
  }

  public bool InputText(string label, string text) {
    bool ret = EffekseerNativePINVOKE.GUIManager_InputText__SWIG_1(swigCPtr, label, text);
    return ret;
  }

  public bool InputTextMultiline(string label, string text) {
    bool ret = EffekseerNativePINVOKE.GUIManager_InputTextMultiline(swigCPtr, label, text);
    return ret;
  }

  public bool InputTextWithHint(string label, string text, string hint, InputTextFlags flags) {
    bool ret = EffekseerNativePINVOKE.GUIManager_InputTextWithHint__SWIG_0(swigCPtr, label, text, hint, (int)flags);
    return ret;
  }

  public bool InputTextWithHint(string label, string text, string hint) {
    bool ret = EffekseerNativePINVOKE.GUIManager_InputTextWithHint__SWIG_1(swigCPtr, label, text, hint);
    return ret;
  }

  public string GetInputTextResult() {
    string ret = System.Runtime.InteropServices.Marshal.PtrToStringUni(EffekseerNativePINVOKE.GUIManager_GetInputTextResult(swigCPtr));
    return ret;
  }

  public bool ColorEdit4(string label, float[] col, ColorEditFlags flags) {
    bool ret = EffekseerNativePINVOKE.GUIManager_ColorEdit4__SWIG_0(swigCPtr, label, col, (int)flags);
    return ret;
  }

  public bool ColorEdit4(string label, float[] col) {
    bool ret = EffekseerNativePINVOKE.GUIManager_ColorEdit4__SWIG_1(swigCPtr, label, col);
    return ret;
  }

  public bool CollapsingHeader(string label, TreeNodeFlags flags) {
    bool ret = EffekseerNativePINVOKE.GUIManager_CollapsingHeader__SWIG_0(swigCPtr, label, (int)flags);
    return ret;
  }

  public bool CollapsingHeader(string label) {
    bool ret = EffekseerNativePINVOKE.GUIManager_CollapsingHeader__SWIG_1(swigCPtr, label);
    return ret;
  }

  public bool CollapsingHeaderWithToggle(string label, TreeNodeFlags flags, string toggle_id, ref bool p_checked) {
    bool ret = EffekseerNativePINVOKE.GUIManager_CollapsingHeaderWithToggle(swigCPtr, label, (int)flags, toggle_id, ref p_checked);
    return ret;
  }

  public bool TreeNode(string label) {
    bool ret = EffekseerNativePINVOKE.GUIManager_TreeNode(swigCPtr, label);
    return ret;
  }

  public bool TreeNodeEx(string label, TreeNodeFlags flags) {
    bool ret = EffekseerNativePINVOKE.GUIManager_TreeNodeEx__SWIG_0(swigCPtr, label, (int)flags);
    return ret;
  }

  public bool TreeNodeEx(string label) {
    bool ret = EffekseerNativePINVOKE.GUIManager_TreeNodeEx__SWIG_1(swigCPtr, label);
    return ret;
  }

  public void TreePop() {
    EffekseerNativePINVOKE.GUIManager_TreePop(swigCPtr);
  }

  public void SetNextItemOpen(bool is_open, Cond cond) {
    EffekseerNativePINVOKE.GUIManager_SetNextItemOpen__SWIG_0(swigCPtr, is_open, (int)cond);
  }

  public void SetNextItemOpen(bool is_open) {
    EffekseerNativePINVOKE.GUIManager_SetNextItemOpen__SWIG_1(swigCPtr, is_open);
  }

  public bool TreeNodeEx(string label, bool[] v, TreeNodeFlags flags) {
    bool ret = EffekseerNativePINVOKE.GUIManager_TreeNodeEx__SWIG_2(swigCPtr, label, v, (int)flags);
    return ret;
  }

  public bool TreeNodeEx(string label, bool[] v) {
    bool ret = EffekseerNativePINVOKE.GUIManager_TreeNodeEx__SWIG_3(swigCPtr, label, v);
    return ret;
  }

  public bool Selectable(string label, bool selected, SelectableFlags flags) {
    bool ret = EffekseerNativePINVOKE.GUIManager_Selectable__SWIG_0(swigCPtr, label, selected, (int)flags);
    return ret;
  }

  public bool Selectable(string label, bool selected) {
    bool ret = EffekseerNativePINVOKE.GUIManager_Selectable__SWIG_1(swigCPtr, label, selected);
    return ret;
  }

  public bool Selectable(string label) {
    bool ret = EffekseerNativePINVOKE.GUIManager_Selectable__SWIG_2(swigCPtr, label);
    return ret;
  }

  public bool SelectableContent(string idstr, string label, bool selected, Image thumbnail, float size_x, float size_y, SelectableFlags flags) {
    bool ret = EffekseerNativePINVOKE.GUIManager_SelectableContent__SWIG_0(swigCPtr, idstr, label, selected, Image.getCPtr(thumbnail), size_x, size_y, (int)flags);
    return ret;
  }

  public bool SelectableContent(string idstr, string label, bool selected, Image thumbnail, float size_x, float size_y) {
    bool ret = EffekseerNativePINVOKE.GUIManager_SelectableContent__SWIG_1(swigCPtr, idstr, label, selected, Image.getCPtr(thumbnail), size_x, size_y);
    return ret;
  }

  public void SetTooltip(string text) {
    EffekseerNativePINVOKE.GUIManager_SetTooltip(swigCPtr, text);
  }

  public void BeginTooltip() {
    EffekseerNativePINVOKE.GUIManager_BeginTooltip(swigCPtr);
  }

  public void EndTooltip() {
    EffekseerNativePINVOKE.GUIManager_EndTooltip(swigCPtr);
  }

  public bool BeginTabBar(string idstr) {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginTabBar(swigCPtr, idstr);
    return ret;
  }

  public void EndTabBar() {
    EffekseerNativePINVOKE.GUIManager_EndTabBar(swigCPtr);
  }

  public bool BeginTabItem(string label) {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginTabItem(swigCPtr, label);
    return ret;
  }

  public void EndTabItem() {
    EffekseerNativePINVOKE.GUIManager_EndTabItem(swigCPtr);
  }

  public bool BeginMainMenuBar() {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginMainMenuBar(swigCPtr);
    return ret;
  }

  public void EndMainMenuBar() {
    EffekseerNativePINVOKE.GUIManager_EndMainMenuBar(swigCPtr);
  }

  public bool BeginMenuBar() {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginMenuBar(swigCPtr);
    return ret;
  }

  public void EndMenuBar() {
    EffekseerNativePINVOKE.GUIManager_EndMenuBar(swigCPtr);
  }

  public bool BeginMenu(string label, bool enabled) {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginMenu__SWIG_0(swigCPtr, label, enabled);
    return ret;
  }

  public bool BeginMenu(string label) {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginMenu__SWIG_1(swigCPtr, label);
    return ret;
  }

  public void EndMenu() {
    EffekseerNativePINVOKE.GUIManager_EndMenu(swigCPtr);
  }

  public bool MenuItem(string label, string shortcut, bool selected, bool enabled) {
    bool ret = EffekseerNativePINVOKE.GUIManager_MenuItem__SWIG_0(swigCPtr, label, shortcut, selected, enabled);
    return ret;
  }

  public bool MenuItem(string label, string shortcut, bool selected) {
    bool ret = EffekseerNativePINVOKE.GUIManager_MenuItem__SWIG_1(swigCPtr, label, shortcut, selected);
    return ret;
  }

  public bool MenuItem(string label, string shortcut) {
    bool ret = EffekseerNativePINVOKE.GUIManager_MenuItem__SWIG_2(swigCPtr, label, shortcut);
    return ret;
  }

  public bool MenuItem(string label) {
    bool ret = EffekseerNativePINVOKE.GUIManager_MenuItem__SWIG_3(swigCPtr, label);
    return ret;
  }

  public bool MenuItem(string label, string shortcut, ref bool p_selected, bool enabled) {
    bool ret = EffekseerNativePINVOKE.GUIManager_MenuItem__SWIG_4(swigCPtr, label, shortcut, ref p_selected, enabled);
    return ret;
  }

  public bool MenuItem(string label, string shortcut, ref bool p_selected) {
    bool ret = EffekseerNativePINVOKE.GUIManager_MenuItem__SWIG_5(swigCPtr, label, shortcut, ref p_selected);
    return ret;
  }

  public void OpenPopup(string str_id) {
    EffekseerNativePINVOKE.GUIManager_OpenPopup(swigCPtr, str_id);
  }

  public bool BeginPopup(string str_id, WindowFlags extra_flags) {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginPopup__SWIG_0(swigCPtr, str_id, (int)extra_flags);
    return ret;
  }

  public bool BeginPopup(string str_id) {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginPopup__SWIG_1(swigCPtr, str_id);
    return ret;
  }

  public bool BeginPopupModal(string name, ref bool p_open, WindowFlags extra_flags) {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginPopupModal__SWIG_0(swigCPtr, name, ref p_open, (int)extra_flags);
    return ret;
  }

  public bool BeginPopupModal(string name, ref bool p_open) {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginPopupModal__SWIG_1(swigCPtr, name, ref p_open);
    return ret;
  }

  public bool BeginPopupModal(string name) {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginPopupModal__SWIG_2(swigCPtr, name);
    return ret;
  }

  public bool BeginPopupContextItem(string str_id, int mouse_button) {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginPopupContextItem__SWIG_0(swigCPtr, str_id, mouse_button);
    return ret;
  }

  public bool BeginPopupContextItem(string str_id) {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginPopupContextItem__SWIG_1(swigCPtr, str_id);
    return ret;
  }

  public bool BeginPopupContextItem() {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginPopupContextItem__SWIG_2(swigCPtr);
    return ret;
  }

  public void EndPopup() {
    EffekseerNativePINVOKE.GUIManager_EndPopup(swigCPtr);
  }

  public bool IsPopupOpen(string str_id) {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsPopupOpen(swigCPtr, str_id);
    return ret;
  }

  public void CloseCurrentPopup() {
    EffekseerNativePINVOKE.GUIManager_CloseCurrentPopup(swigCPtr);
  }

  public void SetItemDefaultFocus() {
    EffekseerNativePINVOKE.GUIManager_SetItemDefaultFocus(swigCPtr);
  }

  public void SetKeyboardFocusHere(int offset) {
    EffekseerNativePINVOKE.GUIManager_SetKeyboardFocusHere__SWIG_0(swigCPtr, offset);
  }

  public void SetKeyboardFocusHere() {
    EffekseerNativePINVOKE.GUIManager_SetKeyboardFocusHere__SWIG_1(swigCPtr);
  }

  public void ClearAllFonts() {
    EffekseerNativePINVOKE.GUIManager_ClearAllFonts(swigCPtr);
  }

  public void AddFontFromFileTTF(string fontFilepath, string commonCharacterTablePath, string characterTableName, float size_pixels) {
    EffekseerNativePINVOKE.GUIManager_AddFontFromFileTTF(swigCPtr, fontFilepath, commonCharacterTablePath, characterTableName, size_pixels);
  }

  public void AddFontFromAtlasImage(string filename, ushort baseCode, int sizeX, int sizeY, int countX, int countY) {
    EffekseerNativePINVOKE.GUIManager_AddFontFromAtlasImage(swigCPtr, filename, baseCode, sizeX, sizeY, countX, countY);
  }

  public bool BeginChildFrame(uint id, Vec2 size, WindowFlags flags) {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginChildFrame__SWIG_0(swigCPtr, id, Vec2.getCPtr(size), (int)flags);
    if (EffekseerNativePINVOKE.SWIGPendingException.Pending) throw EffekseerNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool BeginChildFrame(uint id, Vec2 size) {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginChildFrame__SWIG_1(swigCPtr, id, Vec2.getCPtr(size));
    if (EffekseerNativePINVOKE.SWIGPendingException.Pending) throw EffekseerNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void EndChildFrame() {
    EffekseerNativePINVOKE.GUIManager_EndChildFrame(swigCPtr);
  }

  public int GetKeyIndex(Key key) {
    int ret = EffekseerNativePINVOKE.GUIManager_GetKeyIndex(swigCPtr, (int)key);
    return ret;
  }

  public bool IsKeyDown(int user_key_index) {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsKeyDown(swigCPtr, user_key_index);
    return ret;
  }

  public bool IsKeyPressed(int user_key_index) {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsKeyPressed(swigCPtr, user_key_index);
    return ret;
  }

  public bool IsKeyReleased(int user_key_index) {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsKeyReleased(swigCPtr, user_key_index);
    return ret;
  }

  public bool IsShiftKeyDown() {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsShiftKeyDown(swigCPtr);
    return ret;
  }

  public bool IsCtrlKeyDown() {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsCtrlKeyDown(swigCPtr);
    return ret;
  }

  public bool IsAltKeyDown() {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsAltKeyDown(swigCPtr);
    return ret;
  }

  public int GetPressedKeyIndex(bool repeat) {
    int ret = EffekseerNativePINVOKE.GUIManager_GetPressedKeyIndex(swigCPtr, repeat);
    return ret;
  }

  public string GetInputCharacters() {
    string ret = System.Runtime.InteropServices.Marshal.PtrToStringUni(EffekseerNativePINVOKE.GUIManager_GetInputCharacters(swigCPtr));
    return ret;
  }

  public bool IsMouseDown(int button) {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsMouseDown(swigCPtr, button);
    return ret;
  }

  public bool IsMouseClicked(int button, bool repeat) {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsMouseClicked(swigCPtr, button, repeat);
    return ret;
  }

  public bool IsMouseReleased(int button) {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsMouseReleased(swigCPtr, button);
    return ret;
  }

  public bool IsMouseDoubleClicked(int button) {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsMouseDoubleClicked(swigCPtr, button);
    return ret;
  }

  public void PushTextWrapPos(float pos) {
    EffekseerNativePINVOKE.GUIManager_PushTextWrapPos(swigCPtr, pos);
  }

  public void PopTextWrapPos() {
    EffekseerNativePINVOKE.GUIManager_PopTextWrapPos(swigCPtr);
  }

  public bool IsItemHovered(float f) {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsItemHovered__SWIG_0(swigCPtr, f);
    return ret;
  }

  public bool IsItemHovered() {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsItemHovered__SWIG_1(swigCPtr);
    return ret;
  }

  public bool IsItemActive() {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsItemActive(swigCPtr);
    return ret;
  }

  public bool IsItemFocused() {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsItemFocused(swigCPtr);
    return ret;
  }

  public bool IsItemClicked(int mouse_button) {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsItemClicked(swigCPtr, mouse_button);
    return ret;
  }

  public bool IsItemEdited() {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsItemEdited(swigCPtr);
    return ret;
  }

  public bool IsItemActivated() {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsItemActivated(swigCPtr);
    return ret;
  }

  public bool IsItemDeactivated() {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsItemDeactivated(swigCPtr);
    return ret;
  }

  public bool IsItemDeactivatedAfterEdit() {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsItemDeactivatedAfterEdit(swigCPtr);
    return ret;
  }

  public bool IsAnyItemActive() {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsAnyItemActive(swigCPtr);
    return ret;
  }

  public bool IsWindowHovered() {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsWindowHovered(swigCPtr);
    return ret;
  }

  public bool IsWindowFocused() {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsWindowFocused(swigCPtr);
    return ret;
  }

  public bool IsAnyWindowHovered() {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsAnyWindowHovered(swigCPtr);
    return ret;
  }

  public bool IsAnyWindowFocused() {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsAnyWindowFocused(swigCPtr);
    return ret;
  }

  public MouseCursor GetMouseCursor() {
    MouseCursor ret = (MouseCursor)EffekseerNativePINVOKE.GUIManager_GetMouseCursor(swigCPtr);
    return ret;
  }

  public void PushID(int int_id) {
    EffekseerNativePINVOKE.GUIManager_PushID(swigCPtr, int_id);
  }

  public void PopID() {
    EffekseerNativePINVOKE.GUIManager_PopID(swigCPtr);
  }

  public bool BeginTable(string str_id, int column, TableFlags flags, Vec2 outer_size, float inner_width) {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginTable__SWIG_0(swigCPtr, str_id, column, (int)flags, Vec2.getCPtr(outer_size), inner_width);
    if (EffekseerNativePINVOKE.SWIGPendingException.Pending) throw EffekseerNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool BeginTable(string str_id, int column, TableFlags flags, Vec2 outer_size) {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginTable__SWIG_1(swigCPtr, str_id, column, (int)flags, Vec2.getCPtr(outer_size));
    if (EffekseerNativePINVOKE.SWIGPendingException.Pending) throw EffekseerNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool BeginTable(string str_id, int column, TableFlags flags) {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginTable__SWIG_2(swigCPtr, str_id, column, (int)flags);
    return ret;
  }

  public bool BeginTable(string str_id, int column) {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginTable__SWIG_3(swigCPtr, str_id, column);
    return ret;
  }

  public void EndTable() {
    EffekseerNativePINVOKE.GUIManager_EndTable(swigCPtr);
  }

  public void TableNextRow(TableRowFlags row_flags, float min_row_height) {
    EffekseerNativePINVOKE.GUIManager_TableNextRow__SWIG_0(swigCPtr, (int)row_flags, min_row_height);
  }

  public void TableNextRow(TableRowFlags row_flags) {
    EffekseerNativePINVOKE.GUIManager_TableNextRow__SWIG_1(swigCPtr, (int)row_flags);
  }

  public void TableNextRow() {
    EffekseerNativePINVOKE.GUIManager_TableNextRow__SWIG_2(swigCPtr);
  }

  public bool TableNextColumn() {
    bool ret = EffekseerNativePINVOKE.GUIManager_TableNextColumn(swigCPtr);
    return ret;
  }

  public bool TableSetColumnIndex(int column_n) {
    bool ret = EffekseerNativePINVOKE.GUIManager_TableSetColumnIndex(swigCPtr, column_n);
    return ret;
  }

  public void TableSetupColumn(string label, TableColumnFlags flags, float init_width_or_weight, uint user_id) {
    EffekseerNativePINVOKE.GUIManager_TableSetupColumn__SWIG_0(swigCPtr, label, (int)flags, init_width_or_weight, user_id);
  }

  public void TableSetupColumn(string label, TableColumnFlags flags, float init_width_or_weight) {
    EffekseerNativePINVOKE.GUIManager_TableSetupColumn__SWIG_1(swigCPtr, label, (int)flags, init_width_or_weight);
  }

  public void TableSetupColumn(string label, TableColumnFlags flags) {
    EffekseerNativePINVOKE.GUIManager_TableSetupColumn__SWIG_2(swigCPtr, label, (int)flags);
  }

  public void TableSetupColumn(string label) {
    EffekseerNativePINVOKE.GUIManager_TableSetupColumn__SWIG_3(swigCPtr, label);
  }

  public void TableSetupScrollFreeze(int cols, int rows) {
    EffekseerNativePINVOKE.GUIManager_TableSetupScrollFreeze(swigCPtr, cols, rows);
  }

  public void TableHeadersRow() {
    EffekseerNativePINVOKE.GUIManager_TableHeadersRow(swigCPtr);
  }

  public void TableHeader(string label) {
    EffekseerNativePINVOKE.GUIManager_TableHeader(swigCPtr, label);
  }

  public int TableGetColumnCount() {
    int ret = EffekseerNativePINVOKE.GUIManager_TableGetColumnCount(swigCPtr);
    return ret;
  }

  public int TableGetColumnIndex() {
    int ret = EffekseerNativePINVOKE.GUIManager_TableGetColumnIndex(swigCPtr);
    return ret;
  }

  public int TableGetRowIndex() {
    int ret = EffekseerNativePINVOKE.GUIManager_TableGetRowIndex(swigCPtr);
    return ret;
  }

  public string TableGetColumnName(int column_n) {
    string ret = EffekseerNativePINVOKE.GUIManager_TableGetColumnName__SWIG_0(swigCPtr, column_n);
    return ret;
  }

  public string TableGetColumnName() {
    string ret = EffekseerNativePINVOKE.GUIManager_TableGetColumnName__SWIG_1(swigCPtr);
    return ret;
  }

  public TableColumnFlags TableGetColumnFlags(int column_n) {
    TableColumnFlags ret = (TableColumnFlags)EffekseerNativePINVOKE.GUIManager_TableGetColumnFlags__SWIG_0(swigCPtr, column_n);
    return ret;
  }

  public TableColumnFlags TableGetColumnFlags() {
    TableColumnFlags ret = (TableColumnFlags)EffekseerNativePINVOKE.GUIManager_TableGetColumnFlags__SWIG_1(swigCPtr);
    return ret;
  }

  public void TableSetColumnEnabled(int column_n, bool v) {
    EffekseerNativePINVOKE.GUIManager_TableSetColumnEnabled(swigCPtr, column_n, v);
  }

  public void TableSetBgColor(TableBgTarget target, uint color, int column_n) {
    EffekseerNativePINVOKE.GUIManager_TableSetBgColor__SWIG_0(swigCPtr, (int)target, color, column_n);
  }

  public void TableSetBgColor(TableBgTarget target, uint color) {
    EffekseerNativePINVOKE.GUIManager_TableSetBgColor__SWIG_1(swigCPtr, (int)target, color);
  }

  public float GetHoveredIDTimer() {
    float ret = EffekseerNativePINVOKE.GUIManager_GetHoveredIDTimer(swigCPtr);
    return ret;
  }

  public void DrawLineBackground(float height, uint col) {
    EffekseerNativePINVOKE.GUIManager_DrawLineBackground(swigCPtr, height, col);
  }

  public bool BeginFullscreen(string label) {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginFullscreen(swigCPtr, label);
    return ret;
  }

  public bool BeginDock(string label, string tabLabel, ref bool p_open, bool allowClose, WindowFlags extra_flags) {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginDock(swigCPtr, label, tabLabel, ref p_open, allowClose, (int)extra_flags);
    return ret;
  }

  public void EndDock() {
    EffekseerNativePINVOKE.GUIManager_EndDock(swigCPtr);
  }

  public uint BeginDockLayout() {
    uint ret = EffekseerNativePINVOKE.GUIManager_BeginDockLayout(swigCPtr);
    return ret;
  }

  public void EndDockLayout() {
    EffekseerNativePINVOKE.GUIManager_EndDockLayout(swigCPtr);
  }

  public void DockSplitNode(uint nodeId, DockSplitDir dir, float sizeRatio, ref uint outId1, ref uint outId2) {
    EffekseerNativePINVOKE.GUIManager_DockSplitNode(swigCPtr, nodeId, (int)dir, sizeRatio, ref outId1, ref outId2);
  }

  public void DockSetNodeFlags(uint nodeId, DockNodeFlags flags) {
    EffekseerNativePINVOKE.GUIManager_DockSetNodeFlags(swigCPtr, nodeId, (int)flags);
  }

  public void DockSetWindow(uint nodeId, string windowName) {
    EffekseerNativePINVOKE.GUIManager_DockSetWindow(swigCPtr, nodeId, windowName);
  }

  public bool IsDockFocused() {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsDockFocused(swigCPtr);
    return ret;
  }

  public bool IsDockVisibled() {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsDockVisibled(swigCPtr);
    return ret;
  }

  public bool IsDockWindowed() {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsDockWindowed(swigCPtr);
    return ret;
  }

  public void SetDockFocus(string label) {
    EffekseerNativePINVOKE.GUIManager_SetDockFocus(swigCPtr, label);
  }

  public bool IsHoveredOnFCurve(float[] keys, float[] values, float[] leftHandleKeys, float[] leftHandleValues, float[] rightHandleKeys, float[] rightHandleValues, int[] interporations, FCurveEdgeType startEdge, FCurveEdgeType endEdge, uint col, int count) {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsHoveredOnFCurve(swigCPtr, keys, values, leftHandleKeys, leftHandleValues, rightHandleKeys, rightHandleValues, interporations, (int)startEdge, (int)endEdge, col, count);
    return ret;
  }

  public bool IsHoveredOnFCurvePoint(float[] keys, float[] values, int count, ref int hovered) {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsHoveredOnFCurvePoint(swigCPtr, keys, values, count, ref hovered);
    return ret;
  }

  public bool IsFCurvePanning() {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsFCurvePanning(swigCPtr);
    return ret;
  }

  public Vec2 GetCurrentFCurveFieldPosition() {
    Vec2 ret = new Vec2(EffekseerNativePINVOKE.GUIManager_GetCurrentFCurveFieldPosition(swigCPtr), true);
    return ret;
  }

  public bool BeginFCurve(int id, Vec2 size, float current, Vec2 scale, Vec2 min_kv, Vec2 max_kv) {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginFCurve(swigCPtr, id, Vec2.getCPtr(size), current, Vec2.getCPtr(scale), Vec2.getCPtr(min_kv), Vec2.getCPtr(max_kv));
    if (EffekseerNativePINVOKE.SWIGPendingException.Pending) throw EffekseerNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void EndFCurve() {
    EffekseerNativePINVOKE.GUIManager_EndFCurve(swigCPtr);
  }

  public bool FCurve(int fcurve_id, float[] keys, float[] values, float[] leftHandleKeys, float[] leftHandleValues, float[] rightHandleKeys, float[] rightHandleValues, int[] interporations, FCurveEdgeType startEdge, FCurveEdgeType endEdge, byte[] kv_selected, int count, float defaultValue, bool isLocked, bool canControl, uint col, bool selected, float v_min, float v_max, ref int newCount, ref bool newSelected, ref float movedX, ref float movedY, ref int changedType) {
    bool ret = EffekseerNativePINVOKE.GUIManager_FCurve(swigCPtr, fcurve_id, keys, values, leftHandleKeys, leftHandleValues, rightHandleKeys, rightHandleValues, interporations, (int)startEdge, (int)endEdge, kv_selected, count, defaultValue, isLocked, canControl, col, selected, v_min, v_max, ref newCount, ref newSelected, ref movedX, ref movedY, ref changedType);
    return ret;
  }

  public bool StartSelectingAreaFCurve() {
    bool ret = EffekseerNativePINVOKE.GUIManager_StartSelectingAreaFCurve(swigCPtr);
    return ret;
  }

  public bool AddFCurvePoint(Vec2 v, float[] keys, float[] values, float[] leftHandleKeys, float[] leftHandleValues, float[] rightHandleKeys, float[] rightHandleValues, int[] interporations, byte[] kv_selected, int count, ref int newCount) {
    bool ret = EffekseerNativePINVOKE.GUIManager_AddFCurvePoint(swigCPtr, Vec2.getCPtr(v), keys, values, leftHandleKeys, leftHandleValues, rightHandleKeys, rightHandleValues, interporations, kv_selected, count, ref newCount);
    if (EffekseerNativePINVOKE.SWIGPendingException.Pending) throw EffekseerNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool RemoveFCurvePoint(Vec2 v, float[] keys, float[] values, float[] leftHandleKeys, float[] leftHandleValues, float[] rightHandleKeys, float[] rightHandleValues, int[] interporations, byte[] kv_selected, int count, ref int newCount) {
    bool ret = EffekseerNativePINVOKE.GUIManager_RemoveFCurvePoint(swigCPtr, Vec2.getCPtr(v), keys, values, leftHandleKeys, leftHandleValues, rightHandleKeys, rightHandleValues, interporations, kv_selected, count, ref newCount);
    if (EffekseerNativePINVOKE.SWIGPendingException.Pending) throw EffekseerNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool BeginDragDropSource() {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginDragDropSource(swigCPtr);
    return ret;
  }

  public bool SetDragDropPayload(string type, byte[] data, int size) {
    bool ret = EffekseerNativePINVOKE.GUIManager_SetDragDropPayload(swigCPtr, type, data, size);
    return ret;
  }

  public void EndDragDropSource() {
    EffekseerNativePINVOKE.GUIManager_EndDragDropSource(swigCPtr);
  }

  public bool BeginDragDropTarget() {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginDragDropTarget(swigCPtr);
    return ret;
  }

  public bool AcceptDragDropPayload(string type, byte[] data_output, int data_output_size, ref int size) {
    bool ret = EffekseerNativePINVOKE.GUIManager_AcceptDragDropPayload(swigCPtr, type, data_output, data_output_size, ref size);
    return ret;
  }

  public void EndDragDropTarget() {
    EffekseerNativePINVOKE.GUIManager_EndDragDropTarget(swigCPtr);
  }

  public static DialogSelection show(string message, string title, DialogStyle style, DialogButtons buttons) {
    DialogSelection ret = (DialogSelection)EffekseerNativePINVOKE.GUIManager_show(message, title, (int)style, (int)buttons);
    return ret;
  }

  public static bool IsMacOSX() {
    bool ret = EffekseerNativePINVOKE.GUIManager_IsMacOSX();
    return ret;
  }

  public static void SetIniFilename(string filename) {
    EffekseerNativePINVOKE.GUIManager_SetIniFilename(filename);
  }

  public void Markdown(string text) {
    EffekseerNativePINVOKE.GUIManager_Markdown(swigCPtr, text);
  }

  public bool BeginNodeFrameTimeline() {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginNodeFrameTimeline(swigCPtr);
    return ret;
  }

  public void TimelineNode(string title, int frameStart, int frameEnd) {
    EffekseerNativePINVOKE.GUIManager_TimelineNode(swigCPtr, title, frameStart, frameEnd);
  }

  public void EndNodeFrameTimeline(ref int frameMin, ref int frameMax, ref int currentFrame, ref int selectedEntry, ref int firstFrame) {
    EffekseerNativePINVOKE.GUIManager_EndNodeFrameTimeline(swigCPtr, ref frameMin, ref frameMax, ref currentFrame, ref selectedEntry, ref firstFrame);
  }

  public bool GradientHDR(int gradientID, GradientHDRState state, GradientHDRGUIState guiState, bool isMarkerShown) {
    bool ret = EffekseerNativePINVOKE.GUIManager_GradientHDR(swigCPtr, gradientID, GradientHDRState.getCPtr(state), GradientHDRGUIState.getCPtr(guiState), isMarkerShown);
    if (EffekseerNativePINVOKE.SWIGPendingException.Pending) throw EffekseerNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool BeginPlot(string label, Vec2 size, PlotFlags flags) {
    bool ret = EffekseerNativePINVOKE.GUIManager_BeginPlot(swigCPtr, label, Vec2.getCPtr(size), (int)flags);
    if (EffekseerNativePINVOKE.SWIGPendingException.Pending) throw EffekseerNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void EndPlot() {
    EffekseerNativePINVOKE.GUIManager_EndPlot(swigCPtr);
  }

  public void SetupPlotAxis(PlotAxis axis, string label, PlotAxisFlags flags) {
    EffekseerNativePINVOKE.GUIManager_SetupPlotAxis(swigCPtr, (int)axis, label, (int)flags);
  }

  public void SetupPlotAxisLimits(PlotAxis axis, double vMin, double vMax, Cond cond) {
    EffekseerNativePINVOKE.GUIManager_SetupPlotAxisLimits(swigCPtr, (int)axis, vMin, vMax, (int)cond);
  }

  public void SetupPlotAxisFormat(PlotAxis axis, string fmt) {
    EffekseerNativePINVOKE.GUIManager_SetupPlotAxisFormat(swigCPtr, (int)axis, fmt);
  }

  public void SetupPlotAxisTicks(PlotAxis axis, double vMin, double vMax, int nTicks) {
    EffekseerNativePINVOKE.GUIManager_SetupPlotAxisTicks(swigCPtr, (int)axis, vMin, vMax, nTicks);
  }

  public void PlotLine(string label, double[] xValues, double[] yValues, int count, int offset) {
    EffekseerNativePINVOKE.GUIManager_PlotLine(swigCPtr, label, xValues, yValues, count, offset);
  }

  public void PlotShaded(string label, double[] xValues, double[] yValues, int count, double yRef, int offset) {
    EffekseerNativePINVOKE.GUIManager_PlotShaded(swigCPtr, label, xValues, yValues, count, yRef, offset);
  }

  public void SetNextPlotLineStyle(Vec4 color, float weight) {
    EffekseerNativePINVOKE.GUIManager_SetNextPlotLineStyle(swigCPtr, Vec4.getCPtr(color), weight);
    if (EffekseerNativePINVOKE.SWIGPendingException.Pending) throw EffekseerNativePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetNextPlotFillStyle(Vec4 color, float alphaMod) {
    EffekseerNativePINVOKE.GUIManager_SetNextPlotFillStyle(swigCPtr, Vec4.getCPtr(color), alphaMod);
    if (EffekseerNativePINVOKE.SWIGPendingException.Pending) throw EffekseerNativePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
