//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Effekseer.swig {

public enum ImGuiStyleVarFlags : int {
  Alpha,
  DisabledAlpha,
  WindowPadding,
  WindowRounding,
  WindowBorderSize,
  WindowMinSize,
  WindowTitleAlign,
  ChildRounding,
  ChildBorderSize,
  PopupRounding,
  PopupBorderSize,
  FramePadding,
  FrameRounding,
  FrameBorderSize,
  ItemSpacing,
  ItemInnerSpacing,
  IndentSpacing,
  CellPadding,
  ScrollbarSize,
  ScrollbarRounding,
  GrabMinSize,
  GrabRounding,
  TabRounding,
  ButtonTextAlign,
  SelectableTextAlign,
  LayoutAlign
}

}
