//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Effekseer.swig {

public enum ImGuiStyleVarFlags : int {
  Alpha = ImGuiStyleVar_Alpha,
  DisabledAlpha = ImGuiStyleVar_DisabledAlpha,
  WindowPadding = ImGuiStyleVar_WindowPadding,
  WindowRounding = ImGuiStyleVar_WindowRounding,
  WindowBorderSize = ImGuiStyleVar_WindowBorderSize,
  WindowMinSize = ImGuiStyleVar_WindowMinSize,
  WindowTitleAlign = ImGuiStyleVar_WindowTitleAlign,
  ChildRounding = ImGuiStyleVar_ChildRounding,
  ChildBorderSize = ImGuiStyleVar_ChildBorderSize,
  PopupRounding = ImGuiStyleVar_PopupRounding,
  PopupBorderSize = ImGuiStyleVar_PopupBorderSize,
  FramePadding = ImGuiStyleVar_FramePadding,
  FrameRounding = ImGuiStyleVar_FrameRounding,
  FrameBorderSize = ImGuiStyleVar_FrameBorderSize,
  ItemSpacing = ImGuiStyleVar_ItemSpacing,
  ItemInnerSpacing = ImGuiStyleVar_ItemInnerSpacing,
  IndentSpacing = ImGuiStyleVar_IndentSpacing,
  CellPadding = ImGuiStyleVar_CellPadding,
  ScrollbarSize = ImGuiStyleVar_ScrollbarSize,
  ScrollbarRounding = ImGuiStyleVar_ScrollbarRounding,
  GrabMinSize = ImGuiStyleVar_GrabMinSize,
  GrabRounding = ImGuiStyleVar_GrabRounding,
  TabRounding = ImGuiStyleVar_TabRounding,
  ButtonTextAlign = ImGuiStyleVar_ButtonTextAlign,
  SelectableTextAlign = ImGuiStyleVar_SelectableTextAlign,
  LayoutAlign = ImGuiStyleVar_LayoutAlign
}

}
