//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Effekseer.swig {

public enum InputTextFlags {
  None = ImGuiInputTextFlags_None,
  CharsDecimal = ImGuiInputTextFlags_CharsDecimal,
  CharsHexadecimal = ImGuiInputTextFlags_CharsHexadecimal,
  CharsUppercase = ImGuiInputTextFlags_CharsUppercase,
  CharsNoBlank = ImGuiInputTextFlags_CharsNoBlank,
  AutoSelectAll = ImGuiInputTextFlags_AutoSelectAll,
  EnterReturnsTrue = ImGuiInputTextFlags_EnterReturnsTrue,
  CallbackCompletion = ImGuiInputTextFlags_CallbackCompletion,
  CallbackHistory = ImGuiInputTextFlags_CallbackHistory,
  CallbackAlways = ImGuiInputTextFlags_CallbackAlways,
  CallbackCharFilter = ImGuiInputTextFlags_CallbackCharFilter,
  AllowTabInput = ImGuiInputTextFlags_AllowTabInput,
  CtrlEnterForNewLine = ImGuiInputTextFlags_CtrlEnterForNewLine,
  NoHorizontalScroll = ImGuiInputTextFlags_NoHorizontalScroll,
  AlwaysInsertMode = ImGuiInputTextFlags_AlwaysOverwrite,
  ReadOnly = ImGuiInputTextFlags_ReadOnly,
  Password = ImGuiInputTextFlags_Password,
  NoUndoRedo = ImGuiInputTextFlags_NoUndoRedo,
  CharsScientific = ImGuiInputTextFlags_CharsScientific
}

}
