//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Effekseer.swig {

public enum InputTextFlags {
  None = 0,
  CharsDecimal = 1 << 0,
  CharsHexadecimal = 1 << 1,
  CharsScientific = 1 << 2,
  CharsUppercase = 1 << 3,
  CharsNoBlank = 1 << 4,
  AutoSelectAll = 1 << 12,
  EnterReturnsTrue = 1 << 6,
  CallbackCompletion = 1 << 18,
  CallbackHistory = 1 << 19,
  CallbackAlways = 1 << 20,
  CallbackCharFilter = 1 << 21,
  AllowTabInput = 1 << 5,
  CtrlEnterForNewLine = 1 << 8,
  NoHorizontalScroll = 1 << 15,
  AlwaysInsertMode = 1 << 11,
  ReadOnly = 1 << 9,
  Password = 1 << 10,
  NoUndoRedo = 1 << 16
}

}
