//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Effekseer.swig {

public enum PlotFlags : int {
  None = 0,
  NoTitle = 1 << 0,
  NoLegend = 1 << 1,
  NoMouseText = 1 << 2,
  NoInputs = 1 << 3,
  NoMenus = 1 << 4,
  NoBoxSelect = 1 << 5,
  NoFrame = 1 << 6,
  Equal = 1 << 7,
  Crosshairs = 1 << 8,
  NoChild = 0,
  AntiAliased = 0,
  CanvasOnly = (1 << 0)|(1 << 1)|(1 << 4)|(1 << 5)|(1 << 2)
}

}
