//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Effekseer.swig {

public enum PlotAxisFlags : int {
  None = 0,
  NoLabel = 1 << 0,
  NoGridLines = 1 << 1,
  NoTickMarks = 1 << 2,
  NoTickLabels = 1 << 3,
  NoInitialFit = 1 << 4,
  NoMenus = 1 << 5,
  Opposite = 1 << 6,
  Foreground = 1 << 7,
  LogScale = 1 << 8,
  Time = 1 << 9,
  Invert = 1 << 10,
  AutoFit = 1 << 11,
  RangeFit = 1 << 12,
  LockMin = 1 << 13,
  LockMax = 1 << 14,
  Lock = LockMin|LockMax,
  NoDecorations = NoLabel|NoGridLines|NoTickMarks|NoTickLabels,
  AuxDefault = NoGridLines|Opposite
}

}
