//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Effekseer.swig {

public class PostEffectParameter : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PostEffectParameter(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PostEffectParameter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(PostEffectParameter obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~PostEffectParameter() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          EffekseerNativePINVOKE.delete_PostEffectParameter(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public bool BloomEnabled {
    set {
      EffekseerNativePINVOKE.PostEffectParameter_BloomEnabled_set(swigCPtr, value);
    } 
    get {
      bool ret = EffekseerNativePINVOKE.PostEffectParameter_BloomEnabled_get(swigCPtr);
      return ret;
    } 
  }

  public float BoomIntensity {
    set {
      EffekseerNativePINVOKE.PostEffectParameter_BoomIntensity_set(swigCPtr, value);
    } 
    get {
      float ret = EffekseerNativePINVOKE.PostEffectParameter_BoomIntensity_get(swigCPtr);
      return ret;
    } 
  }

  public float BloomThreshold {
    set {
      EffekseerNativePINVOKE.PostEffectParameter_BloomThreshold_set(swigCPtr, value);
    } 
    get {
      float ret = EffekseerNativePINVOKE.PostEffectParameter_BloomThreshold_get(swigCPtr);
      return ret;
    } 
  }

  public float BloomSoftKnee {
    set {
      EffekseerNativePINVOKE.PostEffectParameter_BloomSoftKnee_set(swigCPtr, value);
    } 
    get {
      float ret = EffekseerNativePINVOKE.PostEffectParameter_BloomSoftKnee_get(swigCPtr);
      return ret;
    } 
  }

  public int ToneMapAlgorithm {
    set {
      EffekseerNativePINVOKE.PostEffectParameter_ToneMapAlgorithm_set(swigCPtr, value);
    } 
    get {
      int ret = EffekseerNativePINVOKE.PostEffectParameter_ToneMapAlgorithm_get(swigCPtr);
      return ret;
    } 
  }

  public float ToneMapExposure {
    set {
      EffekseerNativePINVOKE.PostEffectParameter_ToneMapExposure_set(swigCPtr, value);
    } 
    get {
      float ret = EffekseerNativePINVOKE.PostEffectParameter_ToneMapExposure_get(swigCPtr);
      return ret;
    } 
  }

  public PostEffectParameter() : this(EffekseerNativePINVOKE.new_PostEffectParameter(), true) {
  }

}

}
