//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Effekseer.swig {

public enum SelectableFlags {
  None = 0,
  DontClosePopups = 1 << 0,
  SpanAllColumns = 1 << 1,
  AllowDoubleClick = 1 << 2
}

}
