//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Effekseer.swig {

public enum TableFlags : int {
  None = 0,
  Resizable = 1 << 0,
  Reorderable = 1 << 1,
  Hideable = 1 << 2,
  Sortable = 1 << 3,
  NoSavedSettings = 1 << 4,
  ContextMenuInBody = 1 << 5,
  RowBg = 1 << 6,
  BordersInnerH = 1 << 7,
  BordersOuterH = 1 << 8,
  BordersInnerV = 1 << 9,
  BordersOuterV = 1 << 10,
  BordersH = BordersInnerH|BordersOuterH,
  BordersV = BordersInnerV|BordersOuterV,
  BordersInner = BordersInnerV|BordersInnerH,
  BordersOuter = BordersOuterV|BordersOuterH,
  Borders = BordersInner|BordersOuter,
  NoBordersInBody = 1 << 11,
  NoBordersInBodyUntilResize = 1 << 12,
  SizingFixedFit = 1 << 13,
  SizingFixedSame = 2 << 13,
  SizingStretchProp = 3 << 13,
  SizingStretchSame = 4 << 13,
  NoHostExtendX = 1 << 16,
  NoHostExtendY = 1 << 17,
  NoKeepColumnsVisible = 1 << 18,
  PreciseWidths = 1 << 19,
  NoClip = 1 << 20,
  PadOuterX = 1 << 21,
  NoPadOuterX = 1 << 22,
  NoPadInnerX = 1 << 23,
  ScrollX = 1 << 24,
  ScrollY = 1 << 25,
  SortMulti = 1 << 26,
  SortTristate = 1 << 27
}

}
