//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Effekseer.swig {

public class ViewerParamater : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ViewerParamater(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ViewerParamater obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ViewerParamater obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ViewerParamater() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          EffekseerNativePINVOKE.delete_ViewerParamater(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int GuideWidth {
    set {
      EffekseerNativePINVOKE.ViewerParamater_GuideWidth_set(swigCPtr, value);
    } 
    get {
      int ret = EffekseerNativePINVOKE.ViewerParamater_GuideWidth_get(swigCPtr);
      return ret;
    } 
  }

  public int GuideHeight {
    set {
      EffekseerNativePINVOKE.ViewerParamater_GuideHeight_set(swigCPtr, value);
    } 
    get {
      int ret = EffekseerNativePINVOKE.ViewerParamater_GuideHeight_get(swigCPtr);
      return ret;
    } 
  }

  public bool RendersGuide {
    set {
      EffekseerNativePINVOKE.ViewerParamater_RendersGuide_set(swigCPtr, value);
    } 
    get {
      bool ret = EffekseerNativePINVOKE.ViewerParamater_RendersGuide_get(swigCPtr);
      return ret;
    } 
  }

  public DistortionType Distortion {
    set {
      EffekseerNativePINVOKE.ViewerParamater_Distortion_set(swigCPtr, (int)value);
    } 
    get {
      DistortionType ret = (DistortionType)EffekseerNativePINVOKE.ViewerParamater_Distortion_get(swigCPtr);
      return ret;
    } 
  }

  public RenderingMethodType RenderingMode {
    set {
      EffekseerNativePINVOKE.ViewerParamater_RenderingMode_set(swigCPtr, (int)value);
    } 
    get {
      RenderingMethodType ret = (RenderingMethodType)EffekseerNativePINVOKE.ViewerParamater_RenderingMode_get(swigCPtr);
      return ret;
    } 
  }

  public ViewerParamater() : this(EffekseerNativePINVOKE.new_ViewerParamater(), true) {
  }

}

}
