//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Effekseer.swig {

public enum WindowFlags : int {
  None = ImGuiWindowFlags_None,
  NoTitleBar = ImGuiWindowFlags_NoTitleBar,
  NoResize = ImGuiWindowFlags_NoResize,
  NoMove = ImGuiWindowFlags_NoMove,
  NoScrollbar = ImGuiWindowFlags_NoScrollbar,
  NoScrollWithMouse = ImGuiWindowFlags_NoScrollWithMouse,
  NoCollapse = ImGuiWindowFlags_NoCollapse,
  AlwaysAutoResize = ImGuiWindowFlags_AlwaysAutoResize,
  NoSavedSettings = ImGuiWindowFlags_NoSavedSettings,
  NoMouseInputs = ImGuiWindowFlags_NoMouseInputs,
  NoInputs = ImGuiWindowFlags_NoInputs,
  MenuBar = ImGuiWindowFlags_MenuBar,
  HorizontalScrollbar = ImGuiWindowFlags_HorizontalScrollbar,
  NoFocusOnAppearing = ImGuiWindowFlags_NoFocusOnAppearing,
  NoBringToFrontOnFocus = ImGuiWindowFlags_NoBringToFrontOnFocus,
  AlwaysVerticalScrollbar = ImGuiWindowFlags_AlwaysVerticalScrollbar,
  AlwaysHorizontalScrollbar = ImGuiWindowFlags_AlwaysHorizontalScrollbar,
  AlwaysUseWindowPadding = ImGuiWindowFlags_None,
  NoNavInputs = ImGuiWindowFlags_NoNavInputs,
  NoNavFocus = ImGuiWindowFlags_NoNavFocus
}

}
