//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Effekseer.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Effekseer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Effekseerについて に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutEffekseer {
            get {
                return ResourceManager.GetString("AboutEffekseer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   引力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AttractionForces {
            get {
                return ResourceManager.GetString("AttractionForces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切断時、自動接続を一定時間ごとに行う に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoConnect {
            get {
                return ResourceManager.GetString("AutoConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap BackStep {
            get {
                object obj = ResourceManager.GetObject("BackStep", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   描画共通 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasicRenderSettings {
            get {
                return ResourceManager.GetString("BasicRenderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   共通 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasicSettings {
            get {
                return ResourceManager.GetString("BasicSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   振る舞い に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Behavior {
            get {
                return ResourceManager.GetString("Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カメラの種類&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CameraMode {
            get {
                return ResourceManager.GetString("CameraMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   視点操作 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CameraSettings {
            get {
                return ResourceManager.GetString("CameraSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   補完 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Complement {
            get {
                return ResourceManager.GetString("Complement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}] は変更されています。保存しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmSaveChanged {
            get {
                return ResourceManager.GetString("ConfirmSaveChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カリング に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Culling {
            get {
                return ResourceManager.GetString("Culling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   解除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   振幅 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Deviation {
            get {
                return ResourceManager.GetString("Deviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切断 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了フレーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EndFrame {
            get {
                return ResourceManager.GetString("EndFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AVIとして出力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExportAsAvi {
            get {
                return ResourceManager.GetString("ExportAsAvi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GIFアニメーションとして出力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExportAsGifAnimation {
            get {
                return ResourceManager.GetString("ExportAsGifAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   連番画像として出力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExportAsImages {
            get {
                return ResourceManager.GetString("ExportAsImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1枚にまとめて出力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExportAsSingleImage {
            get {
                return ResourceManager.GetString("ExportAsSingleImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力フレーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExportedFrame {
            get {
                return ResourceManager.GetString("ExportedFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fカーブ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FCurves {
            get {
                return ResourceManager.GetString("FCurves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルビューア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileViewer {
            get {
                return ResourceManager.GetString("FileViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力形式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フレーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Frame {
            get {
                return ResourceManager.GetString("Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力頻度(フレーム毎) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Frequency_Frame {
            get {
                return ResourceManager.GetString("Frequency_Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中心,振幅 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Gauss {
            get {
                return ResourceManager.GetString("Gauss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   生成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GenerateAlpha {
            get {
                return ResourceManager.GetString("GenerateAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   縦幅 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘルプ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IconBehavior {
            get {
                object obj = ResourceManager.GetObject("IconBehavior", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IconCommon {
            get {
                object obj = ResourceManager.GetObject("IconCommon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IconCulling {
            get {
                object obj = ResourceManager.GetObject("IconCulling", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IconFCurve {
            get {
                object obj = ResourceManager.GetObject("IconFCurve", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IconFileViewer {
            get {
                object obj = ResourceManager.GetObject("IconFileViewer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IconGenerationLocation {
            get {
                object obj = ResourceManager.GetObject("IconGenerationLocation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IconLocation {
            get {
                object obj = ResourceManager.GetObject("IconLocation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IconLocationAbs {
            get {
                object obj = ResourceManager.GetObject("IconLocationAbs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IconNetwork {
            get {
                object obj = ResourceManager.GetObject("IconNetwork", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IconNodeTree {
            get {
                object obj = ResourceManager.GetObject("IconNodeTree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IconOption {
            get {
                object obj = ResourceManager.GetObject("IconOption", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IconRecorder {
            get {
                object obj = ResourceManager.GetObject("IconRecorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IconRenderer {
            get {
                object obj = ResourceManager.GetObject("IconRenderer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IconRendererCommon {
            get {
                object obj = ResourceManager.GetObject("IconRendererCommon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IconRotation {
            get {
                object obj = ResourceManager.GetObject("IconRotation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IconScale {
            get {
                object obj = ResourceManager.GetObject("IconScale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IconSound {
            get {
                object obj = ResourceManager.GetObject("IconSound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IconViewer {
            get {
                object obj = ResourceManager.GetObject("IconViewer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IconViewPoint {
            get {
                object obj = ResourceManager.GetObject("IconViewPoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   画像ファイル (*.png)|*.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageFilter {
            get {
                return ResourceManager.GetString("ImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無限 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Infinite {
            get {
                return ResourceManager.GetString("Infinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Effekseerについて に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InternalAbout {
            get {
                return ResourceManager.GetString("InternalAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノードの追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InternalAddNode {
            get {
                return ResourceManager.GetString("InternalAddNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ステップ(後) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InternalBaskStep {
            get {
                return ResourceManager.GetString("InternalBaskStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノードのコピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InternalCopy {
            get {
                return ResourceManager.GetString("InternalCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InternalExit {
            get {
                return ResourceManager.GetString("InternalExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノードの挿入 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InternalInsertNode {
            get {
                return ResourceManager.GetString("InternalInsertNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InternalNew {
            get {
                return ResourceManager.GetString("InternalNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InternalOpen {
            get {
                return ResourceManager.GetString("InternalOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サンプルを開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InternalOpenSample {
            get {
                return ResourceManager.GetString("InternalOpenSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上書き保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InternalOverwrite {
            get {
                return ResourceManager.GetString("InternalOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノードの貼り付け に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InternalPaste {
            get {
                return ResourceManager.GetString("InternalPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノード情報の貼り付け に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InternalPasteInfo {
            get {
                return ResourceManager.GetString("InternalPasteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生・一時停止 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InternalPauseOrResume {
            get {
                return ResourceManager.GetString("InternalPauseOrResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   やり直し に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InternalRedo {
            get {
                return ResourceManager.GetString("InternalRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノードの削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InternalRemoveNode {
            get {
                return ResourceManager.GetString("InternalRemoveNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前をつけて保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InternalSaveAs {
            get {
                return ResourceManager.GetString("InternalSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ステップ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InternalStep {
            get {
                return ResourceManager.GetString("InternalStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   停止 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InternalStop {
            get {
                return ResourceManager.GetString("InternalStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   元に戻す に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InternalUndo {
            get {
                return ResourceManager.GetString("InternalUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘルプを表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InternalViewHelp {
            get {
                return ResourceManager.GetString("InternalViewHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   左 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読込 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   背景透明化の方法 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MakeTransparent {
            get {
                return ResourceManager.GetString("MakeTransparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最大 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中心 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mean {
            get {
                return ResourceManager.GetString("Mean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最小 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   モデルファイル (*.efkmodel,fbx,mqo)|*.efkmodel;*.fbx;*mqo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelFilter {
            get {
                return ResourceManager.GetString("ModelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ネットワーク に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Network {
            get {
                return ResourceManager.GetString("Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NetworkAddress {
            get {
                return ResourceManager.GetString("NetworkAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   状態：接続済 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NetworkConnected {
            get {
                return ResourceManager.GetString("NetworkConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   状態：未接続 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NetworkDisconnected {
            get {
                return ResourceManager.GetString("NetworkDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   状態： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NetworkState {
            get {
                return ResourceManager.GetString("NetworkState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap NodeEmpty {
            get {
                object obj = ResourceManager.GetObject("NodeEmpty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap NodeModel {
            get {
                object obj = ResourceManager.GetObject("NodeModel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap NodeRibbon {
            get {
                object obj = ResourceManager.GetObject("NodeRibbon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap NodeRing {
            get {
                object obj = ResourceManager.GetObject("NodeRing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap NodeSprite {
            get {
                object obj = ResourceManager.GetObject("NodeSprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap NodeTrack {
            get {
                object obj = ResourceManager.GetObject("NodeTrack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   ノードツリー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NodeTree {
            get {
                return ResourceManager.GetString("NodeTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   なし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   絶対パスでありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotAbsolutePathError {
            get {
                return ResourceManager.GetString("NotAbsolutePathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オフセット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オプション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Pause {
            get {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Play {
            get {
                object obj = ResourceManager.GetObject("Play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   再生 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PlayString {
            get {
                return ResourceManager.GetString("PlayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ポート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   視点への距離 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PoVDistance {
            get {
                return ResourceManager.GetString("PoVDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エフェクトプロジェクト (*.efkproj)|*.efkproj に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProjectFilter {
            get {
                return ResourceManager.GetString("ProjectFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最大,最小 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最近使用したファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RecentFiles {
            get {
                return ResourceManager.GetString("RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   録画 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   録画 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Recorder {
            get {
                return ResourceManager.GetString("Recorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   描画 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Render {
            get {
                return ResourceManager.GetString("Render", resourceCulture);
            }
        }
        
        /// <summary>
        ///   描画 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RenderSettings {
            get {
                return ResourceManager.GetString("RenderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   倍率再設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ResetMaginification {
            get {
                return ResourceManager.GetString("ResetMaginification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウインドウ位置を初期化 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ResetWindow {
            get {
                return ResourceManager.GetString("ResetWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   録画範囲(解像度) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   右 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回転 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Rotation {
            get {
                return ResourceManager.GetString("Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サンプリング に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sampling {
            get {
                return ResourceManager.GetString("Sampling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡大 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ送信 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SendData {
            get {
                return ResourceManager.GetString("SendData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   録画範囲を表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShowGuide {
            get {
                return ResourceManager.GetString("ShowGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音声ファイル (*.wav)|*.wav に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SoundFilter {
            get {
                return ResourceManager.GetString("SoundFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   生成方法 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpawningMethod {
            get {
                return ResourceManager.GetString("SpawningMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始フレーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartFrame {
            get {
                return ResourceManager.GetString("StartFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Step {
            get {
                object obj = ResourceManager.GetObject("Step", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   編集時にデータを送信する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TransmitDataOnEdit {
            get {
                return ResourceManager.GetString("TransmitDataOnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読み込み時にデータを送信する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TransmitDataOnLoad {
            get {
                return ResourceManager.GetString("TransmitDataOnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存時にデータを送信する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TransmitDataOnSave {
            get {
                return ResourceManager.GetString("TransmitDataOnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///    *変更あり に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   元の画像 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UseOriginalImage {
            get {
                return ResourceManager.GetString("UseOriginalImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ビュワー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Viewer {
            get {
                return ResourceManager.GetString("Viewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ビュワー操作 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls {
            get {
                return ResourceManager.GetString("ViewerControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   焦点 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Viewpoint {
            get {
                return ResourceManager.GetString("Viewpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   横幅 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウインドウ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   x に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   横方向枚数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XCount {
            get {
                return ResourceManager.GetString("XCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X軸回転 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XRotation {
            get {
                return ResourceManager.GetString("XRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   y に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y軸回転 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YRotation {
            get {
                return ResourceManager.GetString("YRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画面拡大率 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
