// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Effekseer.FB
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct BasicSettings : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static BasicSettings GetRootAsBasicSettings(ByteBuffer _bb) { return GetRootAsBasicSettings(_bb, new BasicSettings()); }
  public static BasicSettings GetRootAsBasicSettings(ByteBuffer _bb, BasicSettings obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public BasicSettings __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int RefEqMaxGeneration { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)-1; } }
  public Effekseer.FB.RefMinMax? RefWqLife { get { int o = __p.__offset(6); return o != 0 ? (Effekseer.FB.RefMinMax?)(new Effekseer.FB.RefMinMax()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public Effekseer.FB.RefMinMax? RefWqGenerationTime { get { int o = __p.__offset(8); return o != 0 ? (Effekseer.FB.RefMinMax?)(new Effekseer.FB.RefMinMax()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public Effekseer.FB.RefMinMax? RefWqGenerationTimeOffset { get { int o = __p.__offset(10); return o != 0 ? (Effekseer.FB.RefMinMax?)(new Effekseer.FB.RefMinMax()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public int MaxGeneration { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)1; } }
  public Effekseer.FB.TranslationParentBindType TranslationBindType { get { int o = __p.__offset(14); return o != 0 ? (Effekseer.FB.TranslationParentBindType)__p.bb.GetInt(o + __p.bb_pos) : Effekseer.FB.TranslationParentBindType.TranslationParentBindType_Always; } }
  public Effekseer.FB.BindType RotationBindType { get { int o = __p.__offset(16); return o != 0 ? (Effekseer.FB.BindType)__p.bb.GetInt(o + __p.bb_pos) : Effekseer.FB.BindType.BindType_Always; } }
  public Effekseer.FB.BindType ScalingBindType { get { int o = __p.__offset(18); return o != 0 ? (Effekseer.FB.BindType)__p.bb.GetInt(o + __p.bb_pos) : Effekseer.FB.BindType.BindType_Always; } }
  public int RemoveWhenLifeIsExtinct { get { int o = __p.__offset(20); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)1; } }
  public int RemoveWhenParentIsRemoved { get { int o = __p.__offset(22); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int RemoveWhenChildrenIsExtinct { get { int o = __p.__offset(24); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public Effekseer.FB.IntRange? Life { get { int o = __p.__offset(26); return o != 0 ? (Effekseer.FB.IntRange?)(new Effekseer.FB.IntRange()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public Effekseer.FB.FloatRange? GenerationTime { get { int o = __p.__offset(28); return o != 0 ? (Effekseer.FB.FloatRange?)(new Effekseer.FB.FloatRange()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public Effekseer.FB.FloatRange? GenerationTimeOffset { get { int o = __p.__offset(30); return o != 0 ? (Effekseer.FB.FloatRange?)(new Effekseer.FB.FloatRange()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static Offset<Effekseer.FB.BasicSettings> CreateBasicSettings(FlatBufferBuilder builder,
      int ref_eq_max_generation = -1,
      Effekseer.FB.RefMinMaxT ref_wq_life = null,
      Effekseer.FB.RefMinMaxT ref_wq_generation_time = null,
      Effekseer.FB.RefMinMaxT ref_wq_generation_time_offset = null,
      int max_generation = 1,
      Effekseer.FB.TranslationParentBindType translation_bind_type = Effekseer.FB.TranslationParentBindType.TranslationParentBindType_Always,
      Effekseer.FB.BindType rotation_bind_type = Effekseer.FB.BindType.BindType_Always,
      Effekseer.FB.BindType scaling_bind_type = Effekseer.FB.BindType.BindType_Always,
      int remove_when_life_is_extinct = 1,
      int remove_when_parent_is_removed = 0,
      int remove_when_children_is_extinct = 0,
      Effekseer.FB.IntRangeT life = null,
      Effekseer.FB.FloatRangeT generation_time = null,
      Effekseer.FB.FloatRangeT generation_time_offset = null) {
    builder.StartTable(14);
    BasicSettings.AddGenerationTimeOffset(builder, Effekseer.FB.FloatRange.Pack(builder, generation_time_offset));
    BasicSettings.AddGenerationTime(builder, Effekseer.FB.FloatRange.Pack(builder, generation_time));
    BasicSettings.AddLife(builder, Effekseer.FB.IntRange.Pack(builder, life));
    BasicSettings.AddRemoveWhenChildrenIsExtinct(builder, remove_when_children_is_extinct);
    BasicSettings.AddRemoveWhenParentIsRemoved(builder, remove_when_parent_is_removed);
    BasicSettings.AddRemoveWhenLifeIsExtinct(builder, remove_when_life_is_extinct);
    BasicSettings.AddScalingBindType(builder, scaling_bind_type);
    BasicSettings.AddRotationBindType(builder, rotation_bind_type);
    BasicSettings.AddTranslationBindType(builder, translation_bind_type);
    BasicSettings.AddMaxGeneration(builder, max_generation);
    BasicSettings.AddRefWqGenerationTimeOffset(builder, Effekseer.FB.RefMinMax.Pack(builder, ref_wq_generation_time_offset));
    BasicSettings.AddRefWqGenerationTime(builder, Effekseer.FB.RefMinMax.Pack(builder, ref_wq_generation_time));
    BasicSettings.AddRefWqLife(builder, Effekseer.FB.RefMinMax.Pack(builder, ref_wq_life));
    BasicSettings.AddRefEqMaxGeneration(builder, ref_eq_max_generation);
    return BasicSettings.EndBasicSettings(builder);
  }

  public static void StartBasicSettings(FlatBufferBuilder builder) { builder.StartTable(14); }
  public static void AddRefEqMaxGeneration(FlatBufferBuilder builder, int refEqMaxGeneration) { builder.AddInt(0, refEqMaxGeneration, -1); }
  public static void AddRefWqLife(FlatBufferBuilder builder, Offset<Effekseer.FB.RefMinMax> refWqLifeOffset) { builder.AddStruct(1, refWqLifeOffset.Value, 0); }
  public static void AddRefWqGenerationTime(FlatBufferBuilder builder, Offset<Effekseer.FB.RefMinMax> refWqGenerationTimeOffset) { builder.AddStruct(2, refWqGenerationTimeOffset.Value, 0); }
  public static void AddRefWqGenerationTimeOffset(FlatBufferBuilder builder, Offset<Effekseer.FB.RefMinMax> refWqGenerationTimeOffsetOffset) { builder.AddStruct(3, refWqGenerationTimeOffsetOffset.Value, 0); }
  public static void AddMaxGeneration(FlatBufferBuilder builder, int maxGeneration) { builder.AddInt(4, maxGeneration, 1); }
  public static void AddTranslationBindType(FlatBufferBuilder builder, Effekseer.FB.TranslationParentBindType translationBindType) { builder.AddInt(5, (int)translationBindType, 2); }
  public static void AddRotationBindType(FlatBufferBuilder builder, Effekseer.FB.BindType rotationBindType) { builder.AddInt(6, (int)rotationBindType, 2); }
  public static void AddScalingBindType(FlatBufferBuilder builder, Effekseer.FB.BindType scalingBindType) { builder.AddInt(7, (int)scalingBindType, 2); }
  public static void AddRemoveWhenLifeIsExtinct(FlatBufferBuilder builder, int removeWhenLifeIsExtinct) { builder.AddInt(8, removeWhenLifeIsExtinct, 1); }
  public static void AddRemoveWhenParentIsRemoved(FlatBufferBuilder builder, int removeWhenParentIsRemoved) { builder.AddInt(9, removeWhenParentIsRemoved, 0); }
  public static void AddRemoveWhenChildrenIsExtinct(FlatBufferBuilder builder, int removeWhenChildrenIsExtinct) { builder.AddInt(10, removeWhenChildrenIsExtinct, 0); }
  public static void AddLife(FlatBufferBuilder builder, Offset<Effekseer.FB.IntRange> lifeOffset) { builder.AddStruct(11, lifeOffset.Value, 0); }
  public static void AddGenerationTime(FlatBufferBuilder builder, Offset<Effekseer.FB.FloatRange> generationTimeOffset) { builder.AddStruct(12, generationTimeOffset.Value, 0); }
  public static void AddGenerationTimeOffset(FlatBufferBuilder builder, Offset<Effekseer.FB.FloatRange> generationTimeOffsetOffset) { builder.AddStruct(13, generationTimeOffsetOffset.Value, 0); }
  public static Offset<Effekseer.FB.BasicSettings> EndBasicSettings(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Effekseer.FB.BasicSettings>(o);
  }
  public BasicSettingsT UnPack() {
    var _o = new BasicSettingsT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(BasicSettingsT _o) {
    _o.RefEqMaxGeneration = this.RefEqMaxGeneration;
    _o.RefWqLife = this.RefWqLife.HasValue ? this.RefWqLife.Value.UnPack() : null;
    _o.RefWqGenerationTime = this.RefWqGenerationTime.HasValue ? this.RefWqGenerationTime.Value.UnPack() : null;
    _o.RefWqGenerationTimeOffset = this.RefWqGenerationTimeOffset.HasValue ? this.RefWqGenerationTimeOffset.Value.UnPack() : null;
    _o.MaxGeneration = this.MaxGeneration;
    _o.TranslationBindType = this.TranslationBindType;
    _o.RotationBindType = this.RotationBindType;
    _o.ScalingBindType = this.ScalingBindType;
    _o.RemoveWhenLifeIsExtinct = this.RemoveWhenLifeIsExtinct;
    _o.RemoveWhenParentIsRemoved = this.RemoveWhenParentIsRemoved;
    _o.RemoveWhenChildrenIsExtinct = this.RemoveWhenChildrenIsExtinct;
    _o.Life = this.Life.HasValue ? this.Life.Value.UnPack() : null;
    _o.GenerationTime = this.GenerationTime.HasValue ? this.GenerationTime.Value.UnPack() : null;
    _o.GenerationTimeOffset = this.GenerationTimeOffset.HasValue ? this.GenerationTimeOffset.Value.UnPack() : null;
  }
  public static Offset<Effekseer.FB.BasicSettings> Pack(FlatBufferBuilder builder, BasicSettingsT _o) {
    if (_o == null) return default(Offset<Effekseer.FB.BasicSettings>);
    return CreateBasicSettings(
      builder,
      _o.RefEqMaxGeneration,
      _o.RefWqLife,
      _o.RefWqGenerationTime,
      _o.RefWqGenerationTimeOffset,
      _o.MaxGeneration,
      _o.TranslationBindType,
      _o.RotationBindType,
      _o.ScalingBindType,
      _o.RemoveWhenLifeIsExtinct,
      _o.RemoveWhenParentIsRemoved,
      _o.RemoveWhenChildrenIsExtinct,
      _o.Life,
      _o.GenerationTime,
      _o.GenerationTimeOffset);
  }
};

public class BasicSettingsT
{
  public int RefEqMaxGeneration { get; set; }
  public Effekseer.FB.RefMinMaxT RefWqLife { get; set; }
  public Effekseer.FB.RefMinMaxT RefWqGenerationTime { get; set; }
  public Effekseer.FB.RefMinMaxT RefWqGenerationTimeOffset { get; set; }
  public int MaxGeneration { get; set; }
  public Effekseer.FB.TranslationParentBindType TranslationBindType { get; set; }
  public Effekseer.FB.BindType RotationBindType { get; set; }
  public Effekseer.FB.BindType ScalingBindType { get; set; }
  public int RemoveWhenLifeIsExtinct { get; set; }
  public int RemoveWhenParentIsRemoved { get; set; }
  public int RemoveWhenChildrenIsExtinct { get; set; }
  public Effekseer.FB.IntRangeT Life { get; set; }
  public Effekseer.FB.FloatRangeT GenerationTime { get; set; }
  public Effekseer.FB.FloatRangeT GenerationTimeOffset { get; set; }

  public BasicSettingsT() {
    this.RefEqMaxGeneration = -1;
    this.RefWqLife = new Effekseer.FB.RefMinMaxT();
    this.RefWqGenerationTime = new Effekseer.FB.RefMinMaxT();
    this.RefWqGenerationTimeOffset = new Effekseer.FB.RefMinMaxT();
    this.MaxGeneration = 1;
    this.TranslationBindType = Effekseer.FB.TranslationParentBindType.TranslationParentBindType_Always;
    this.RotationBindType = Effekseer.FB.BindType.BindType_Always;
    this.ScalingBindType = Effekseer.FB.BindType.BindType_Always;
    this.RemoveWhenLifeIsExtinct = 1;
    this.RemoveWhenParentIsRemoved = 0;
    this.RemoveWhenChildrenIsExtinct = 0;
    this.Life = new Effekseer.FB.IntRangeT();
    this.GenerationTime = new Effekseer.FB.FloatRangeT();
    this.GenerationTimeOffset = new Effekseer.FB.FloatRangeT();
  }
}


}
