// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Effekseer.FB.Effect
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct EffectAsset : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static EffectAsset GetRootAsEffectAsset(ByteBuffer _bb) { return GetRootAsEffectAsset(_bb, new EffectAsset()); }
  public static EffectAsset GetRootAsEffectAsset(ByteBuffer _bb, EffectAsset obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EffectAsset __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Effekseer.FB.Effect.TextureProperty? Textures(int j) { int o = __p.__offset(4); return o != 0 ? (Effekseer.FB.Effect.TextureProperty?)(new Effekseer.FB.Effect.TextureProperty()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int TexturesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  public Effekseer.FB.Effect.Node? RootNode { get { int o = __p.__offset(6); return o != 0 ? (Effekseer.FB.Effect.Node?)(new Effekseer.FB.Effect.Node()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Effekseer.FB.Effect.EffectAsset> CreateEffectAsset(FlatBufferBuilder builder,
      VectorOffset texturesOffset = default(VectorOffset),
      Offset<Effekseer.FB.Effect.Node> root_nodeOffset = default(Offset<Effekseer.FB.Effect.Node>)) {
    builder.StartTable(2);
    EffectAsset.AddRootNode(builder, root_nodeOffset);
    EffectAsset.AddTextures(builder, texturesOffset);
    return EffectAsset.EndEffectAsset(builder);
  }

  public static void StartEffectAsset(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddTextures(FlatBufferBuilder builder, VectorOffset texturesOffset) { builder.AddOffset(0, texturesOffset.Value, 0); }
  public static VectorOffset CreateTexturesVector(FlatBufferBuilder builder, Offset<Effekseer.FB.Effect.TextureProperty>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateTexturesVectorBlock(FlatBufferBuilder builder, Offset<Effekseer.FB.Effect.TextureProperty>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartTexturesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddRootNode(FlatBufferBuilder builder, Offset<Effekseer.FB.Effect.Node> rootNodeOffset) { builder.AddOffset(1, rootNodeOffset.Value, 0); }
  public static Offset<Effekseer.FB.Effect.EffectAsset> EndEffectAsset(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Effekseer.FB.Effect.EffectAsset>(o);
  }
  public static void FinishEffectAssetBuffer(FlatBufferBuilder builder, Offset<Effekseer.FB.Effect.EffectAsset> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedEffectAssetBuffer(FlatBufferBuilder builder, Offset<Effekseer.FB.Effect.EffectAsset> offset) { builder.FinishSizePrefixed(offset.Value); }
  public EffectAssetT UnPack() {
    var _o = new EffectAssetT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(EffectAssetT _o) {
    _o.Textures = new List<Effekseer.FB.Effect.TexturePropertyT>();
    for (var _j = 0; _j < this.TexturesLength; ++_j) {_o.Textures.Add(this.Textures(_j).HasValue ? this.Textures(_j).Value.UnPack() : null);}
    _o.RootNode = this.RootNode.HasValue ? this.RootNode.Value.UnPack() : null;
  }
  public static Offset<Effekseer.FB.Effect.EffectAsset> Pack(FlatBufferBuilder builder, EffectAssetT _o) {
    if (_o == null) return default(Offset<Effekseer.FB.Effect.EffectAsset>);
    var _textures = default(VectorOffset);
    if (_o.Textures != null) {
      var __textures = new Offset<Effekseer.FB.Effect.TextureProperty>[_o.Textures.Count];
      for (var _j = 0; _j < __textures.Length; ++_j) { __textures[_j] = Effekseer.FB.Effect.TextureProperty.Pack(builder, _o.Textures[_j]); }
      _textures = CreateTexturesVector(builder, __textures);
    }
    var _root_node = _o.RootNode == null ? default(Offset<Effekseer.FB.Effect.Node>) : Effekseer.FB.Effect.Node.Pack(builder, _o.RootNode);
    return CreateEffectAsset(
      builder,
      _textures,
      _root_node);
  }
};

public class EffectAssetT
{
  public List<Effekseer.FB.Effect.TexturePropertyT> Textures { get; set; }
  public Effekseer.FB.Effect.NodeT RootNode { get; set; }

  public EffectAssetT() {
    this.Textures = null;
    this.RootNode = null;
  }
  public static EffectAssetT DeserializeFromBinary(byte[] fbBuffer) {
    return EffectAsset.GetRootAsEffectAsset(new ByteBuffer(fbBuffer)).UnPack();
  }
  public byte[] SerializeToBinary() {
    var fbb = new FlatBufferBuilder(0x10000);
    EffectAsset.FinishEffectAssetBuffer(fbb, EffectAsset.Pack(fbb, this));
    return fbb.DataBuffer.ToSizedArray();
  }
}


}
