//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.6
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Effekseer.swig {

public class GUIManager : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GUIManager(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GUIManager obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~GUIManager() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          EffekseerNativePINVOKE.delete_GUIManager(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public GUIManager() : this(EffekseerNativePINVOKE.new_GUIManager(), true) {
  }

  public bool Initialize(string title, int width, int height, bool isSRGBMode) {
    bool ret = EffekseerNativePINVOKE.GUIManager_Initialize(swigCPtr, title, width, height, isSRGBMode);
    return ret;
  }

  public void Terminate() {
    EffekseerNativePINVOKE.GUIManager_Terminate(swigCPtr);
  }

  public bool DoEvents() {
    bool ret = EffekseerNativePINVOKE.GUIManager_DoEvents(swigCPtr);
    return ret;
  }

  public void Present() {
    EffekseerNativePINVOKE.GUIManager_Present(swigCPtr);
  }

  public void ResetGUI() {
    EffekseerNativePINVOKE.GUIManager_ResetGUI(swigCPtr);
  }

  public void RenderGUI() {
    EffekseerNativePINVOKE.GUIManager_RenderGUI(swigCPtr);
  }

  public System.IntPtr GetNativeHandle() { return EffekseerNativePINVOKE.GUIManager_GetNativeHandle(swigCPtr); }

  public bool Begin(string name, bool[] p_open) {
    bool ret = EffekseerNativePINVOKE.GUIManager_Begin(swigCPtr, name, p_open);
    return ret;
  }

  public void End() {
    EffekseerNativePINVOKE.GUIManager_End(swigCPtr);
  }

  public void PushItemWidth(float item_width) {
    EffekseerNativePINVOKE.GUIManager_PushItemWidth(swigCPtr, item_width);
  }

  public void PopItemWidth() {
    EffekseerNativePINVOKE.GUIManager_PopItemWidth(swigCPtr);
  }

  public void Separator() {
    EffekseerNativePINVOKE.GUIManager_Separator(swigCPtr);
  }

  public void SameLine() {
    EffekseerNativePINVOKE.GUIManager_SameLine(swigCPtr);
  }

  public void Text(string text) {
    EffekseerNativePINVOKE.GUIManager_Text(swigCPtr, text);
  }

  public bool Button(string label) {
    bool ret = EffekseerNativePINVOKE.GUIManager_Button(swigCPtr, label);
    return ret;
  }

  public bool DragInt(string label, int[] v, float v_speed, int v_min, int v_max) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt__SWIG_0(swigCPtr, label, v, v_speed, v_min, v_max);
    return ret;
  }

  public bool DragInt(string label, int[] v, float v_speed, int v_min) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt__SWIG_1(swigCPtr, label, v, v_speed, v_min);
    return ret;
  }

  public bool DragInt(string label, int[] v, float v_speed) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt__SWIG_2(swigCPtr, label, v, v_speed);
    return ret;
  }

  public bool DragInt(string label, int[] v) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragInt__SWIG_3(swigCPtr, label, v);
    return ret;
  }

  public bool InputInt(string label, int[] v, int step, int step_fast) {
    bool ret = EffekseerNativePINVOKE.GUIManager_InputInt__SWIG_0(swigCPtr, label, v, step, step_fast);
    return ret;
  }

  public bool InputInt(string label, int[] v, int step) {
    bool ret = EffekseerNativePINVOKE.GUIManager_InputInt__SWIG_1(swigCPtr, label, v, step);
    return ret;
  }

  public bool InputInt(string label, int[] v) {
    bool ret = EffekseerNativePINVOKE.GUIManager_InputInt__SWIG_2(swigCPtr, label, v);
    return ret;
  }

  public bool SliderInt(string label, int[] v, int v_min, int v_max) {
    bool ret = EffekseerNativePINVOKE.GUIManager_SliderInt(swigCPtr, label, v, v_min, v_max);
    return ret;
  }

  public bool DragIntRange2(string label, int[] v_current_min, int[] v_current_max, float v_speed, int v_min, int v_max, string display_format, string display_format_max) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragIntRange2__SWIG_0(swigCPtr, label, v_current_min, v_current_max, v_speed, v_min, v_max, display_format, display_format_max);
    return ret;
  }

  public bool DragIntRange2(string label, int[] v_current_min, int[] v_current_max, float v_speed, int v_min, int v_max, string display_format) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragIntRange2__SWIG_1(swigCPtr, label, v_current_min, v_current_max, v_speed, v_min, v_max, display_format);
    return ret;
  }

  public bool DragIntRange2(string label, int[] v_current_min, int[] v_current_max, float v_speed, int v_min, int v_max) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragIntRange2__SWIG_2(swigCPtr, label, v_current_min, v_current_max, v_speed, v_min, v_max);
    return ret;
  }

  public bool DragIntRange2(string label, int[] v_current_min, int[] v_current_max, float v_speed, int v_min) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragIntRange2__SWIG_3(swigCPtr, label, v_current_min, v_current_max, v_speed, v_min);
    return ret;
  }

  public bool DragIntRange2(string label, int[] v_current_min, int[] v_current_max, float v_speed) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragIntRange2__SWIG_4(swigCPtr, label, v_current_min, v_current_max, v_speed);
    return ret;
  }

  public bool DragIntRange2(string label, int[] v_current_min, int[] v_current_max) {
    bool ret = EffekseerNativePINVOKE.GUIManager_DragIntRange2__SWIG_5(swigCPtr, label, v_current_min, v_current_max);
    return ret;
  }

}

}
